SELECT
    sum(LO_REVENUE),
    toYear(LO_ORDERDATE) AS year,
    P_BRAND
FROM lineorder_flat
WHERE P_CATEGORY = 'MFGR#12' AND S_REGION = 'AMERICA'
GROUP BY
    toYear(LO_ORDERDATE),
    P_BRAND
ORDER BY
    toYear(LO_ORDERDATE),
    P_BRAND;
