version: "1.1"

on:
  push:
    branches:
      - release/*
    tags:
      - v*

stages:
  - stage:
      - git-checkout:
          alias: erda-ui
          version: "1.0"
          params:
            depth: 1
  - stage:
      - git-checkout:
          alias: erda-ui-enterprise
          version: "1.0"
          params:
            uri: https://erda.cloud/erda/dop/erda-project/erda-ui-enterprise-mirror
            branch: ${{ outputs.erda-ui.branch }}
            depth: 1
  - stage:
      - extract-repo-version:
          alias: ui-version
          params:
            git_dir: ${{ dirs.erda-ui }}
  - stage:
      - js-build:
          alias: build-erda-ui
          version: "1.0"
          params:
            node_version: 12
            build_cmd:
              - cd ${{ dirs.erda-ui }}
              - npm i @erda-ui/cli@1.4.x -g
              - cp -r ${{ dirs.erda-ui-enterprise }}/* ${{ dirs.erda-ui }}/modules
              - cd ${{ dirs.erda-ui }}/modules/admin && npm i
              - cd ${{ dirs.erda-ui }}/modules/fdp && npm i
              - cd ${{ dirs.erda-ui }}/shell && npm run online-extra-logic
              - cd ${{ dirs.erda-ui }}
              - erda-ui init --online
              - erda-ui build --online
              - cp -r ${{ dirs.erda-ui }}/{public,scheduler} $WORKDIR
          caches:
            - key: "{{basePath}}/build-cache-ee/{{endPath}}"
              path: ${{ dirs.erda-ui }}/node_modules
          resources:
            cpu: 2
            mem: 6144
  - stage:
      - dockerfile:
          alias: build-erda-ui-image
          version: "1.0"
          params:
            workdir: ${{ dirs.build-erda-ui }}
            path: ${{ dirs.erda-ui }}/Dockerfile
            image:
              name: ui-ee
              tag: ${{ outputs.ui-version.image_tag }}
            registry:
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
              password: ${{ configs.docker_registry_password }}
          resources:
            cpu: 2
            mem: 2048
  - stage:
      - release:
          alias: release-ui-enterprise
          version: "1.0"
          params:
            dice_yml: ${{ dirs.erda-ui-enterprise }}/erda.yml
            image:
              ui: ${{ outputs.build-erda-ui-image.image }}
          resources:
            cpu: 0.5
            mem: 512
  - stage:
      - js-build:
          alias: build-erda-ui-ce
          params:
            node_version: 12
            build_cmd:
              - export FOR_COMMUNITY=true
              - cd ${{ dirs.erda-ui }}
              - npm i @erda-ui/cli@1.4.x -g
              - erda-ui init --online --ce
              - erda-ui build --online --ce
              - cp -r ${{ dirs.erda-ui }}/{public,scheduler} $WORKDIR
          caches:
            - key: "{{basePath}}/build-cache-ce/{{endPath}}"
              path: ${{ dirs.erda-ui }}/node_modules
          resources:
            cpu: 2
            mem: 6144
  - stage:
      - dockerfile:
          alias: build-erda-ui-ce-image
          version: "1.0"
          params:
            workdir: ${{ dirs.build-erda-ui-ce }}
            path: ${{ dirs.erda-ui }}/Dockerfile
            image:
              name: ui-ce
              tag: ${{ outputs.ui-version.image_tag }}
            registry:
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
              password: ${{ configs.docker_registry_password }}
          resources:
            cpu: 2
            mem: 2048
