
DROP TABLE IF EXISTS cnch_test;
CREATE TABLE cnch_test (s String) ENGINE = CnchMergeTree order by s;
SELECT * FROM cnch_test LIMIT 1;
SELECT * FROM cnch_test;
DETACH TABLE cnch_test PERMANENTLY;
ATTACH TABLE cnch_test;
SELECT * FROM cnch_test;
SELECT * FROM cnch_test LIMIT 1;
INSERT INTO cnch_test VALUES ('Hello'), ('World');
SELECT * FROM cnch_test LIMIT 1;
DETACH TABLE cnch_test PERMANENTLY;
ATTACH TABLE cnch_test;
SELECT * FROM cnch_test LIMIT 1;
SELECT * FROM cnch_test;
DETACH TABLE cnch_test PERMANENTLY;
ATTACH TABLE cnch_test;
SELECT * FROM cnch_test;
SELECT * FROM cnch_test LIMIT 1;
DROP TABLE cnch_test;
