DROP DATABASE IF EXISTS test_rename_from;
DROP DATABASE IF EXISTS test_rename_to;
CREATE DATABASE test_rename_from;
CREATE TABLE test_rename_from.test (d Date, a String, b String) ENGINE = CnchMergeTree() PARTITION BY toYYYYMM(d) ORDER BY d SETTINGS index_granularity = 8192;
INSERT INTO test_rename_from.test VALUES ('2021-01-01', 'hello', 'world');
SELECT * FROM test_rename_from.test;
RENAME DATABASE test_rename_from TO test_rename_to;
SELECT * FROM test_rename_to.test;
DROP DATABASE IF EXISTS test_rename_from;
DROP DATABASE IF EXISTS test_rename_to;