DROP DATABASE IF EXISTS test_read_only;
CREATE DATABASE test_read_only;
USE test_read_only;
CREATE TABLE cnch_select_readonly(a String, b String) ENGINE = CnchMergeTree() ORDER BY a;
INSERT INTO cnch_select_readonly values ('a', '1'), ('b', '2'), ('c', '3');
SELECT a, b FROM cnch_select_readonly SETTINGS readonly = 0;
SELECT a, b FROM cnch_select_readonly SETTINGS readonly = 1;
SELECT a, b FROM cnch_select_readonly SETTINGS readonly = 2;
DROP TABLE cnch_select_readonly;
DROP DATABASE test_read_only;