SELECT '--case 1';
SELECT * FROM numbers(3) WHERE 1 = number ORDER BY number ;
SELECT '--case 2';
SELECT * FROM numbers(3) WHERE 1 != number ORDER BY number ;
SELECT '--case 3';
SELECT * FROM numbers(3) WHERE 1 < number ORDER BY number ;
SELECT '--case 4';
SELECT * FROM numbers(3) WHERE 1 <= number ORDER BY number ;
SELECT '--case 5';
SELECT * FROM numbers(3) WHERE 1 > number ORDER BY number ;
SELECT '--case 6';
SELECT * FROM numbers(3) WHERE 1 >= number ORDER BY number ;
