apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-mqtt
  namespace: devices
spec:
  sku: "testMQTT" 
  connection: Ethernet
  address: 192.168.62.231:1883 # change this accordingly
  protocol: MQTT
  protocolSettings:
    MQTTSetting:
