{
 "title": "Hive",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"hive\"},instance)"
    }
   },
   {
    "name": "env",
    "label": "surroundings",
    "query": {
     "query": "label_values(process_start_time_seconds,env)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "HiveServer2启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"hiveserver2\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HiveMetaStore启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"hivemetastore\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HiveServer2堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{job=\"hiveserver2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HiveMetaStore分配堆大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{job=\"hivemetastore\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HiveServer2堆内存使用趋势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"hiveserver2\"}",
     "legendFormat": "已用堆内存"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"hiveserver2\"}",
     "legendFormat": "最大堆内存"
    }
   ]
  },
  {
   "title": "HiveServer2 GC时间趋势图",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"hiveserver2\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "HiveMetaStore堆内存使用趋势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"hivemetastore\"}",
     "legendFormat": "已用堆内存"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"hivemetastore\"}",
     "legendFormat": "最大堆内存"
    }
   ]
  },
  {
   "title": "HiveMetaStore GC时间趋势图",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"hivemetastore\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}