{
 "title": "Ranger",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"rangeradmin\"}"
    }
   ]
  },
  {
   "title": "RangerAdmin启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"rangeradmin\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RangerAdmin运行时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"rangeradmin\"}"
    }
   ]
  },
  {
   "title": "RangerAdmin堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{job=\"rangeradmin\",area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RangerAdmin堆内存使用趋势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"rangeradmin\"}",
     "legendFormat": "已用堆内存"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"rangeradmin\"}",
     "legendFormat": "最大堆内存"
    }
   ]
  },
  {
   "title": "RangerAdmin GC时间趋势图",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"rangeradmin\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}