{
 "title": "Trino",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(up{job=\"trino\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TrinoCoordinator启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"trinocoordinator\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TrinoCoordinator运行时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"trinocoordinator\"}"
    }
   ]
  },
  {
   "title": "Trino最大堆内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{job=\"trinocoordinator\",area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TrinoCoordinator堆内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"trinocoordinator\"}*100/jvm_memory_bytes_max{area=\"heap\",job=\"trinocoordinator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线Worker数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"trinoworker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TrinoCoordinator堆内存使用趋势",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"trinocoordinator\"}",
     "legendFormat": "已用内存"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"trinocoordinator\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"trinocoordinator\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "TrinoCoordinator GC时间趋势图",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"trinocoordinator\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "TrinoWorker内存使用率",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"trinoworker\"}*100/jvm_memory_bytes_max{area=\"heap\",job=\"trinoworker\"}",
     "legendFormat": "broker"
    }
   ]
  }
 ]
}