apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: volume.trait.abm.io
spec:
  className: com.alibaba.tesla.appmanager.trait.plugin.VolumeTrait
  runtime: pre
  appliesToWorkloads:
    - "*"
  definitionRef:
    name: volume.k8s.schema.abm.io
  example:
    pvc:
      metadata:
        name: appmanager-tmp-claim
        namespace: apsara-bigdata-manager
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
        storageClassName: yoda-lvm
    volumeMounts:
      - mountPath: "/tmp"
        name: appmanager-tmp
    volumes:
      - name: appmanager-tmp
        persistentVolumeClaim:
          claimName: appmanager-tmp-claim
