# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn  clean install  -DskipTests
    - name: upload build result
      run: mkdir staging && cp cloudeon-assembly/target/cloudeon-assembly-1.0.0-release.zip staging/cloudeon-assembly-1.0.0-release.zip &&  cp cloudeon-assembly/target/cloudeon-assembly-1.0.0-release.tar.gz staging/cloudeon-assembly-1.0.0-release.tar.gz
    - uses: actions/upload-artifact@v1
      with:
        name: cloudeon-assembly-1.0.0-release.zip
        path: staging/cloudeon-assembly-1.0.0-release.zip
    - uses: actions/upload-artifact@v1
      with:
        name: cloudeon-assembly-1.0.0-release.tar.gz
        path: staging/cloudeon-assembly-1.0.0-release.tar.gz

    - name: Build the Docker image
      run: cp -r cloudeon-assembly/target/cloudeon-assembly-1.0.0-release ./docker
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: peterpoker/cloudeon
        tag_with_ref: true
        tags: latest
        path: docker/
    - name: build docker image for aliyun
      run:  docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password  ${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com  && docker build -f docker/Dockerfile -t cloudeon:1.0.0 ./docker  && docker tag cloudeon:1.0.0 registry.cn-hangzhou.aliyuncs.com/udh/cloudeon:1.0.0  && docker push registry.cn-hangzhou.aliyuncs.com/udh/cloudeon:1.0.0
