import BASE_SETTING from "./setting/BASE_SETTING";
import GOODS_SETTING from "./setting/GOODS_SETTING";
import ORDER_SETTING from "./setting/ORDER_SETTING";
import POINT_SETTING from "./setting/POINT_SETTING";
import KUAIDI_SETTING from "./setting/KUAIDI_SETTING";
import OSS_SETTING from "./setting/OSS_SETTING";
import SMS_SETTING from "./setting/SMS_SETTING";
import IM_SETTING from "./setting/IM_SETTING";
import WITHDRAWAL_SETTING from "./setting/WITHDRAWAL_SETTING";
import ALIPAY_PAYMENT from "./pay/ALIPAY_PAYMENT";
import WECHAT_PAYMENT from "./pay/WECHAT_PAYMENT";
import PAYMENT_SUPPORT from "./pay/PAYMENT_SUPPORT";
import WECHAT_CONNECT from "./authLogin/WECHAT_CONNECT";
import QQ_CONNECT from "./authLogin/QQ_CONNECT";

export default {
  BASE_SETTING,
  GOODS_SETTING,
  ORDER_SETTING,
  POINT_SETTING,
  KUAIDI_SETTING,
  OSS_SETTING,
  SMS_SETTING,
  IM_SETTING,
  WITHDRAWAL_SETTING,
  PAYMENT_SUPPORT,
  WECHAT_PAYMENT,
  ALIPAY_PAYMENT,
  WECHAT_CONNECT,
  QQ_CONNECT
};
