create table instancedetail
(
    instance_id          varchar(32)    default ''     not null,
    order_id             varchar(32)    default ''     not null,
    batch_msg            varchar(255)   default ''     null ,
    "type"                int    default 0      not null ,
    ext                  text                          not null ,
    waitinginstance_id   varchar(32)    default ''     null,
    kind                 smallint       default 1      not null ,
    parent_id            varchar(32)    default ''     null,
    pricemode            smallint       default 1      not null ,
    "name"                 varchar(50)    default ''     not null,
    makename             varchar(50)    default ''     null,
    taste                varchar(255)   default ''     null,
    spec_detail_name     varchar(50)    default ''     null,
    num                  decimal(10, 2) default 0.00   not null,
    account_num          decimal(12, 4) default 0.0000 not null,
    unit                 varchar(50)    default ''     null,
    account_unit         varchar(50)    default ''     null,
    price                decimal(18, 2) default 0.00   not null,
    member_price         decimal(18, 2) default 0.00   not null,
    fee                  decimal(18, 2) default 0.00   not null,
    ratio                decimal(10, 2) default 0.00   not null,
    ratio_fee            decimal(18, 2) default 0.00   not null,
    ratio_cause          varchar(255)   default ''     null,
    status               smallint       default 1      not null ,
    kindmenu_id          varchar(32)    default ''     null,
    kindmenu_name        varchar(50)    default ''     null,
    menu_id              varchar(32)    default ''     null,
    memo                 varchar(255)   default ''     null,
    is_ratio             smallint       default 0      null,
    entity_id            varchar(32)    default ''     not null,
    is_valid             smallint       default 1      not null,
    create_time          bigint         default 0      null,
    op_time              bigint         default 0      null,
    last_ver             bigint         default 0      not null,
    load_time            int            default 0      not null ,
    modify_time          int            default 0      not null ,
    draw_status          int        default 0      not null,
    bookmenu_id          varchar(32)    default ''     null,
    make_id              varchar(32)    default ''     null,
    make_price           decimal(18, 2) default 0.00   not null,
    prodplan_id          varchar(32)    default ''     null,
    is_wait              int        default 0      not null,
    specdetail_id        varchar(32)    default ''     null,
    specdetail_price     decimal(18, 2) default 0.00   not null,
    makeprice_mode       int        default 0      not null,
    original_price       varchar(32)    default ''     null,
    is_buynumber_changed int        default 0      not null,
    ratio_operator_id    varchar(32)    default ''     null,
    child_id             varchar(32)    default ''     null,
    kind_bookmenu_id     varchar(32)    default ''     null,
    specprice_mode       int        default 0      not null,
    worker_id            varchar(32)    default ''     null,
    is_backauth          int        default 1      not null,
    service_fee_mode     int        default 0      not null,
    service_fee          varchar(32)    default ''     null,
    orign_id             varchar(32)    default ''     null,
    addition_price       decimal(18, 2) default 0.00   not null,
    has_addition         int        default 0      not null,
    seat_id              varchar(32)    default ''     null,
    CONSTRAINT production primary key(instance_id)
)