neo4j-admin import \
    --database=stock.db \
    --ignore-duplicate-nodes=true \
    --ignore-missing-nodes=true \
    --id-type=string \
    --nodes=data/import/executive.csv \
    --nodes=data/import/stock.csv \
    --nodes=data/import/industry.csv \
    --nodes=data/import/concept.csv \
    --relationships=data/import/executive_stock.csv \
    --relationships=data/import/stock_industry.csv \
    --relationships=data/import/stock_concept.csv