const nodes = [
  {
    id: 'nodes0',
    label: '15158301473',
    shape: 'CircleNode',
    data: { id: 'nodes0-0', label: '15158301473' },
    style: { nodeSize: 24, primaryColor: '#4cf6c1', fontSize: 10, icon: 'phone' },
    x: 50,
    y: 50,
  },
  {
    id: 'nodes1',
    label: '宁波达米网络科技有限公司',
    shape: 'CircleNode',
    data: { id: 'nodes1-0', label: '宁波达米网络科技有限公司' },
    style: { nodeSize: 30, primaryColor: '#f6b32f', fontSize: 16, icon: 'company' },
    x: 400,
    y: 70,
  },
  {
    id: 'nodes2',
    label: '蔡东旭',
    shape: 'CircleNode',
    data: { id: 'nodes2-0', label: '蔡东旭' },
    style: { nodeSize: 30, primaryColor: '#263ef6', fontSize: 12, icon: 'person' },
    x: 600,
    y: 150,
  },
  {
    id: 'nodes3',
    label: '王晴',
    shape: 'CircleNode',
    data: { id: 'nodes3-0', label: '王晴' },
    style: { nodeSize: 30, primaryColor: '#f63446', fontSize: 12, icon: 'person' },
    x: 100,
    y: 220,
  },
  {
    id: 'nodes4',
    label: '胡科艇',
    shape: 'CircleNode',
    data: { id: 'nodes4-0', label: '胡科艇' },
    style: { nodeSize: 30, primaryColor: '#5fa4f6', fontSize: 12, icon: 'person' },
    x: 350,
    y: 260,
  },
  {
    id: 'nodes5',
    label: 'BiliBili-大米评测',
    shape: 'CircleNode',
    data: { id: 'nodes5-0', label: 'BiliBili-大米评测' },
    style: { nodeSize: 30, primaryColor: '#f636cb', fontSize: 12, icon: 'email' },
    x: 790,
    y: 280,
  },
  {
    id: 'nodes6',
    label: '15657806368',
    shape: 'CircleNode',
    data: { id: 'nodes6-0', label: '15657806368' },
    style: { nodeSize: 30, primaryColor: '#4CF6C1', fontSize: 12, icon: 'phone' },
    x: 500,
    y: 300,
  },
  {
    id: 'nodes7',
    label: '宁波大红鹰职业技术学院',
    shape: 'CircleNode',
    data: { id: 'nodes7-0', label: '宁波大红鹰职业技术学院', icon: 'company' },
    style: { nodeSize: 30, primaryColor: '#cccccc', fontSize: 12 },
    x: 150,
    y: 360,
  },
  {
    id: 'nodes8',
    label: '大米',
    shape: 'CircleNode',
    data: { id: 'nodes7-0', label: '大米' },
    style: { nodeSize: 30, primaryColor: '#26f600', fontSize: 12, icon: 'device' },
    x: 630,
    y: 380,
  },
  {
    id: 'nodes9',
    label: '大米评测(www.pingce.net)',
    shape: 'CircleNode',
    data: { id: 'nodes7-0', label: '大米评测(www.pingce.net)' },
    style: { nodeSize: 30, primaryColor: '#f6e5cf', fontSize: 12, icon: 'company' },
    x: 370,
    y: 460,
  },
  {
    id: 'nodes10',
    label: '新浪微博-大米评测',
    shape: 'CircleNode',
    data: { id: 'nodes7-0', label: '新浪微博-大米评测' },
    style: { nodeSize: 30, primaryColor: '#f636cb', fontSize: 12, icon: 'email' },
    x: 720,
    y: 470,
  },
  {
    id: 'nodes11',
    label: '浙江-宁波',
    shape: 'CircleNode',
    data: { id: 'nodes7-0', label: '新浪微博-大米评测' },
    style: { nodeSize: 30, primaryColor: '#f6e5cf', fontSize: 12, icon: 'company' },
    x: 940,
    y: 420,
  },
]
const edges = [
  {
    data: {
      label: '工商电话号码',
      source: 'nodes1',
      target: 'nodes0',
    },
    label: '工商电话号码',
    source: 'nodes1',
    target: 'nodes0',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '股东5%',
      source: 'nodes3',
      target: 'nodes1',
    },
    label: '股东5%',
    source: 'nodes3',
    target: 'nodes1',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '电话',
      source: 'nodes3',
      target: 'nodes0',
    },
    label: '电话',
    source: 'nodes3',
    target: 'nodes0',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '股东（5%）',
      source: 'nodes2',
      target: 'nodes1',
    },
    label: '股东（5%）',
    source: 'nodes2',
    target: 'nodes1',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '大股东（80%）',
      source: 'nodes4',
      target: 'nodes1',
    },
    label: '大股东（80%）',
    source: 'nodes4',
    target: 'nodes1',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '毕业学校',
      source: 'nodes4',
      target: 'nodes7',
    },
    label: '毕业学校',
    source: 'nodes4',
    target: 'nodes7',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '手机号码',
      source: 'nodes4',
      target: 'nodes6',
    },
    label: '手机号码',
    source: 'nodes4',
    target: 'nodes6',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '评测视频暴露了手机号码',
      source: 'nodes5',
      target: 'nodes6',
    },
    label: '评测视频暴露了手机号码',
    source: 'nodes5',
    target: 'nodes6',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '微信',
      source: 'nodes6',
      target: 'nodes8',
    },
    label: '微信',
    source: 'nodes6',
    target: 'nodes8',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '网站备案信息',
      source: 'nodes9',
      target: 'nodes4',
    },
    label: '网站备案信息',
    source: 'nodes9',
    target: 'nodes4',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '博客地址',
      source: 'nodes10',
      target: 'nodes9',
    },
    label: '博客地址',
    source: 'nodes10',
    target: 'nodes9',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '所在地',
      source: 'nodes10',
      target: 'nodes11',
    },
    label: '所在地',
    source: 'nodes10',
    target: 'nodes11',
    shape: 'LineEdge',
  },
  {
    data: {
      label: '',
      source: 'nodes10',
      target: 'nodes5',
    },
    label: '',
    source: 'nodes10',
    target: 'nodes5',
    shape: 'LineEdge',
  },
]
const demoData = { nodes, edges }

export default demoData
