# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG RANGER_DB_TYPE

FROM ranger-base:latest AS ranger-kms

ARG RANGER_VERSION
ARG RANGER_DB_TYPE

COPY ./dist/version                             /home/ranger/dist/
COPY ./dist/ranger-${RANGER_VERSION}-kms.tar.gz /home/ranger/dist/

COPY ./scripts/ranger-kms.sh                                   ${RANGER_SCRIPTS}/
COPY ./scripts/ranger-kms-install-${RANGER_DB_TYPE}.properties ${RANGER_SCRIPTS}/ranger-kms-install.properties

RUN tar xvfz /home/ranger/dist/ranger-${RANGER_VERSION}-kms.tar.gz --directory=${RANGER_HOME} && \
    ln -s ${RANGER_HOME}/ranger-${RANGER_VERSION}-kms ${RANGER_HOME}/kms && \
    rm -f /home/ranger/dist/ranger-${RANGER_VERSION}-kms.tar.gz && \
    cp -f ${RANGER_SCRIPTS}/ranger-kms-install.properties ${RANGER_HOME}/kms/install.properties && \
    mkdir -p /var/run/ranger_kms && \
    mkdir -p /var/log/ranger/kms && \
    mkdir -p /etc/ranger && \
    touch /etc/init.d/ranger-kms && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /etc/init.d/ranger-kms /etc/rc2.d/S88ranger-kms && \
    ln -s /etc/init.d/ranger-kms /etc/rc2.d/K90ranger-kms && \
    ln -s /etc/init.d/ranger-kms /etc/rc3.d/S88ranger-kms && \
    ln -s /etc/init.d/ranger-kms /etc/rc3.d/K90ranger-kms && \
    ln -s ${RANGER_HOME}/kms/ranger-kms-services.sh /usr/bin/ranger-kms-services.sh && \
    chown -R rangerkms:ranger ${RANGER_HOME}/kms/ ${RANGER_SCRIPTS}/ /var/run/ranger_kms/ /var/log/ranger/ && \
    chmod 744 ${RANGER_SCRIPTS}/ranger-kms.sh && \
    mkdir -p /usr/share/java/

FROM ranger-kms AS ranger_postgres
COPY ./downloads/postgresql-42.2.16.jre7.jar          /home/ranger/dist/
RUN  mv /home/ranger/dist/postgresql-42.2.16.jre7.jar /usr/share/java/postgresql.jar

FROM ranger-kms AS ranger_mysql
COPY ./downloads/mysql-connector-java-8.0.28.jar  /home/ranger/dist/
COPY ./downloads/log4jdbc-1.2.jar                 /home/ranger/dist/
RUN  mv /home/ranger/dist/mysql-connector-java-8.0.28.jar /usr/share/java/mysql-connector.jar && \
     mv /home/ranger/dist/log4jdbc-1.2.jar ${RANGER_HOME}/kms/ews/webapp/WEB-INF/lib/log4jdbc-1.2.jar

FROM ranger_${RANGER_DB_TYPE}

ENTRYPOINT [ "/home/ranger/scripts/ranger-kms.sh" ]
