{
 "title": "资源成本运营大盘",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "集群", "query": "prometheus" },
   { "name": "hours", "label": "统计周期", "query": "日 : 24,  周 : 168, 月 : 730" },
   {
    "name": "localStorageGBCost",
    "label": "Cost per Gb hour for attached disks",
    "query": "0.04"
   },
   { "name": "egressCost", "query": "0.12" },
   { "name": "node", "query": { "query": "query_result(kube_node_labels)" } },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(sum(container_memory_working_set_bytes{namespace=\"$namespace\",instance=\"$node\"}) by (pod_name))"
    }
   }
  ]
 },
 "panels": [
  { "title": "集群资源成本看板", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU成本",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node) * avg(node_cpu_hourly_cost) by (node) * $hours + avg(node_gpu_hourly_cost) by (node) * $hours)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存成本",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024 * avg(node_ram_hourly_cost) by (node) * $hours)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "存储成本",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(avg(pv_hourly_cost) by (persistentvolume) * $hours * avg(kube_persistentvolume_capacity_bytes) by (persistentvolume) / 1024 / 1024 / 1024) \n+\nsum(sum(container_fs_limit_bytes{device!=\"tmpfs\", id=\"/\"}) by (instance) / 1024 / 1024 / 1024) * $localStorageGBCost",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "流量成本",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(node_network_transmit_bytes_total{device=\"eth0\"}[60m]) / 1024 / 1024 / 1024) * (60 * 60 ) * $hours * $egressCost ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "总成本",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "# Compute\nsum(\n  avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node) * avg(node_cpu_hourly_cost) by (node) * $hours +\n  avg(node_gpu_hourly_cost) by (node) * $hours\n) +\n\n\n# Memory\nsum(\n  avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024 * avg(node_ram_hourly_cost) by (node) * $hours\n) +\n\n# Storage \nsum(avg(pv_hourly_cost) by (persistentvolume) * $hours * avg(kube_persistentvolume_capacity_bytes) by (persistentvolume) / 1024 / 1024 / 1024) \n+\nsum(sum(container_fs_limit_bytes{device!=\"tmpfs\", id=\"/\"}) by (instance) / 1024 / 1024 / 1024) * $localStorageGBCost\n\n# Net\n+ sum(rate(node_network_transmit_bytes_total{device=\"eth0\"}[60m]) / 1024 / 1024 / 1024) * (60 * 60 ) * $hours * $egressCost ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(\n sum(\n   count(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n   * on (instance) \n   sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n ) \n / \n sum(avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node))\n) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Request利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(avg(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}) by (pod, container)) / sum(avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node)) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(container_memory_usage_bytes{namespace!=\"\", image!=\"\"}) / sum(avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node)) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存Request利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(\n sum(avg(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"}) by (pod, container))\n /\n sum(avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node))\n) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FS存储利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(\n sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"})\n /\n sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"})\n) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PV存储利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum (\n avg(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, namespace)\n + on (persistentvolumeclaim, namespace)\n sum(pod_pvc_allocation) by (persistentvolumeclaim, namespace) or up * 0\n) /\nsum (\n avg(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, namespace)\n + on (persistentvolumeclaim, namespace)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace) or up * 0\n) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "POD总数(RUNNING)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(\n count(avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container!=\"\",container!=\"POD\"}[24h])) by (pod)\n * on (pod) group_right()\n count(kube_pod_container_status_running) by (pod)\n)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node成本统计",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node) * avg(node_cpu_hourly_cost or up * 0) by (node) * $hours",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024 * avg(node_ram_hourly_cost) by (node) * $hours"
    },
    {
     "expr": "sum(label_replace(container_fs_limit_bytes{device!=\"tmpfs\", id=\"/\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node) / 1024 / 1024 / 1024 * $localStorageGBCost"
    },
    {
     "expr": "# CPU  \navg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node) * avg(node_cpu_hourly_cost or up * 0) by (node) * $hours \n+\n# Memory\navg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024 * avg(node_ram_hourly_cost) by (node) * $hours\n+\n# Disk\nsum(label_replace(container_fs_limit_bytes{device!=\"tmpfs\", id=\"/\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node) / 1024 / 1024 / 1024 * $localStorageGBCost"
    }
   ]
  },
  {
   "title": "集群成本趋势图",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(\n  avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node) * avg(node_cpu_hourly_cost) by (node) * $hours\n)",
     "legendFormat": "CPU成本",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum(\n  avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024 * avg(node_ram_hourly_cost) by (node) * $hours\n)",
     "legendFormat": "MEM成本"
    },
    {
     "expr": "sum(avg(pv_hourly_cost) by (persistentvolume) * $hours * avg(kube_persistentvolume_capacity_bytes) by (persistentvolume) / 1024 / 1024 / 1024) \n+\nsum(sum(container_fs_limit_bytes{device!=\"tmpfs\", id=\"/\"}) by (instance) / 1024 / 1024 / 1024) * $localStorageGBCost",
     "legendFormat": "存储成本"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=\"eth0\"}[60m]) / 1024 / 1024 / 1024 ) * (60 * 60 * $hours) * $egressCost ",
     "legendFormat": "流量成本"
    }
   ]
  },
  {
   "title": "CPU利用率趋势图",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n sum(\n   count(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n   * on (instance) \n   sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n ) \n / \n sum(avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node))\n) * 100",
     "legendFormat": "利用率"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}) by (pod, container)) / sum(avg(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"}) by (node)) * 100",
     "legendFormat": "Request利用率"
    },
    {
     "expr": "sum(avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node))",
     "legendFormat": "CPU总核数"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}) by (node, pod))",
     "legendFormat": "Request核数"
    },
    {
     "expr": " sum(\n   count(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n   * on (instance) \n   sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n ) ",
     "legendFormat": "使用核数"
    }
   ]
  },
  {
   "title": "内存利用率趋势图",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "SUM(container_memory_usage_bytes{image!=\"\"}) / sum(avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node)) * 100",
     "legendFormat": "利用率率",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "(\n sum(avg(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"}) by (pod, container))\n /\n sum(avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node))\n) * 100",
     "legendFormat": "Request利用率"
    },
    {
     "expr": "sum(avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024)",
     "legendFormat": "内存总量"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"}) by (pod, container) / 1024 / 1024 / 1024)",
     "legendFormat": "Request内存量"
    },
    {
     "expr": "sum(max(container_memory_usage_bytes{namespace!=\"\"}) by (pod)  / 1024 / 1024 / 1024)",
     "legendFormat": "内存用量"
    }
   ]
  },
  {
   "title": "存储利用率趋势图",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(\n sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"})\n /\n sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"})\n) * 100",
     "legendFormat": "FS利用率",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum (\n avg(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, namespace)\n + on (persistentvolumeclaim, namespace)\n sum(pod_pvc_allocation) by (persistentvolumeclaim, namespace) or up * 0\n) /\nsum (\n avg(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, namespace)\n + on (persistentvolumeclaim, namespace)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace) or up * 0\n) * 100",
     "legendFormat": "PV利用率"
    },
    {
     "expr": "SUM(rate(node_disk_reads_completed_total[10m])) or SUM(rate(node_disk_reads_completed[10m]))",
     "legendFormat": "磁盘读"
    },
    {
     "expr": "SUM(rate(node_disk_writes_completed_total[10m])) or SUM(rate(node_disk_writes_completed[10m]))",
     "legendFormat": "磁盘写"
    }
   ]
  },
  { "title": "Node节点资源看板", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU利用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(\n sum(\n   count(irate(container_cpu_usage_seconds_total{id=\"/\",instance=\"$node\"}[10m]))\n   * on (instance) \n   sum(irate(container_cpu_usage_seconds_total{id=\"/\",instance=\"$node\"}[10m]))\n ) \n / \n avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\", node=\"$node\"})\n) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(container_memory_usage_bytes{namespace!=\"\", image!=\"\",instance=\"$node\"}) / avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\", node=\"$node\"}) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FS存储利用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(\n sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=\"$node\"})\n /\n sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=\"$node\"})\n) * 100",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "POD总数(RUNNING)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(\n count(avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container!=\"\",container!=\"POD\",node=\"$node\"}[24h])) by (pod)\n * on (pod) group_right()\n count(kube_pod_container_status_running) by (pod)\n)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(\n sum(\n   count(irate(container_cpu_usage_seconds_total{id=\"/\",instance=\"$node\"}[10m]))\n   * on (instance) \n   sum(irate(container_cpu_usage_seconds_total{id=\"/\",instance=\"$node\"}[10m]))\n ) \n / \n avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\", node=\"$node\"})\n) * 100",
     "legendFormat": "CPU利用率",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(container_memory_usage_bytes{namespace!=\"\", image!=\"\",instance=\"$node\"}) / avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\", node=\"$node\"}) * 100",
     "legendFormat": "内存利用率",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FS存储",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(\n sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=\"$node\"})\n /\n sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=\"$node\"})\n) * 100",
     "legendFormat": "FS存储利用率",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "磁盘写"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "磁盘读"
    }
   ]
  },
  {
   "title": "节点流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "入流量",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "出流量"
    }
   ]
  },
  {
   "title": "POD资源监控(最近一天平均)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"\",container_name!=\"POD\",pod_name!=\"\",instance=\"$node\"}[24h])) by (pod_name)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum(label_replace(\navg(avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container!=\"\",container!=\"POD\",node=\"$node\"}[24h])) by (pod), \n\"pod_name\",\"$1\",\"pod\",\"(.+)\")) by (pod_name)"
    },
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{container_name!=\"\",container_name!=\"POD\",pod_name!=\"\",instance=\"$node\"}[24h])) by (pod_name)"
    },
    {
     "expr": "sum(label_replace(label_replace(\navg(avg_over_time(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container!=\"\",container!=\"POD\",node=\"$node\"}[24h])) by (pod),\n\"container_name\",\"$1\",\"container\",\"(.+)\"), \"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)\n"
    }
   ]
  },
  { "title": "POD资源成本看板", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Container资源监控",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"\",container_name!=\"POD\",pod_name=\"$pod\",instance=\"$node\"}[$__range])) by (container_name)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum(label_replace(\navg(avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container!=\"\",container!=\"POD\",pod=\"$pod\",node=\"$node\"}[$__range])) by (container), \n\"container_name\",\"$1\",\"container\",\"(.+)\")) by (container_name)"
    },
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{container_name!=\"\",container_name!=\"POD\",pod_name=\"$pod\",instance=\"$node\"}[$__range])) by (container_name)"
    },
    {
     "expr": "sum(label_replace(\navg(avg_over_time(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container!=\"\",container!=\"POD\",pod=\"$pod\",node=\"$node\"}[$__range])) by (container),\n\"container_name\",\"$1\",\"container\",\"(.+)\")\n) by (container_name)\n"
    }
   ]
  },
  {
   "title": "CPU(Container)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\",container_name!=\"\"}[10m])) by (container_name)",
     "legendFormat": "{{ container_name }} (usage)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container}} (request)"
    }
   ]
  },
  {
   "title": "内存(Container)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(avg_over_time(container_memory_usage_bytes{container_name!=\"\",container_name!=\"POD\",pod_name=\"$pod\",instance=\"$node\"}[10m])) by (container_name)",
     "legendFormat": "{{ container_name }} (usage)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container}} (request)"
    }
   ]
  },
  {
   "title": "流量(POD)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[10m])) by (pod_name)",
     "legendFormat": "入流量",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "- avg (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[10m])) by (pod_name)",
     "legendFormat": "出流量"
    }
   ]
  },
  {
   "title": "磁盘IO(POD)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[10m])) by (pod_name)",
     "legendFormat": "磁盘写",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "- avg(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[10m])) by (pod_name)",
     "legendFormat": "磁盘读"
    }
   ]
  }
 ]
}