{
 "title": "Doris Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(up, job)" } },
   {
    "name": "fe_master",
    "query": {
     "query": "query_result(node_info{group=\"fe\", job=\"$cluster_name\", type=\"is_master\"})"
    }
   },
   {
    "name": "fe_instance",
    "query": {
     "query": "up{group=\"fe\", job=\"$cluster_name\"}"
    }
   },
   {
    "name": "be_instance",
    "query": {
     "query": "up{group=\"be\", job=\"$cluster_name\"}"
    }
   },
   { "name": "interval", "query": "1m,2m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Number",
   "type": "stat",
   "description": "Num of  Doris Clusters",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_info{type=\"is_master\"})"
    }
   ]
  },
  {
   "title": "Frontends Status",
   "type": "graph",
   "description": "Dead Frontends will be shown as Colored points.\nIf all Frontends are alive, all points should be Green.",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(up{group=\"fe\"} == 0) +0",
     "legendFormat": "{{job}}-{{instance}}: DEAD"
    },
    {
     "expr": "(up{group=\"fe\"} == 1) +0",
     "legendFormat": "{{job}}-{{instance}}: ALIVE"
    }
   ]
  },
  {
   "title": "Backends status",
   "type": "graph",
   "description": "Dead Backends will be shown as Colored points.\nIf all Backends are alive, all points should be Green.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(up{group=\"be\"} == 0) +0",
     "legendFormat": "{{job}}-{{instance}}: DEAD"
    },
    {
     "expr": "(up{group=\"be\"} == 1) +0",
     "legendFormat": "{{job}}-{{instance}}: ALIVE"
    }
   ]
  },
  {
   "title": "Cluster FE JVM Heap Stat",
   "type": "graph",
   "description": "The JVM heap usage percent of each Frontend of each Doris cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_heap_size_bytes{group=\"fe\", type=\"used\"} * 100) by (instance, job) / sum(jvm_heap_size_bytes{group=\"fe\", type=\"max\"}) by (instance, job)",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster BE CPU Idle",
   "type": "graph",
   "description": "The Backend CPU idle overview of each Doris cluster.\nThe detail Backend CPU idle info can be seen in 'BE' section.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(doris_be_cpu{mode=\"idle\"}[$interval])) by (job)) / (sum(rate(doris_be_cpu[$interval])) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cluster BE Mem Stat",
   "type": "graph",
   "description": "The Backend memory usage overview of each Doris cluster.\nThe detail backend memory usage can be seen in 'BE' section.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(doris_be_memory_allocated_bytes) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cluster QPS Stat",
   "type": "graph",
   "description": "QPS statistic group by cluster.\nThe QPS of each cluster is the sum of all queries processed on all Frontends.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(rate(doris_fe_query_total{group=\"fe\"}[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Disk State",
   "type": "graph",
   "description": "The Disk state. GREEN point means this disk is ONLINE. RED point means this disk is OFFLINE",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(doris_be_disks_state{job=\"$cluster_name\"} == 0)+0",
     "legendFormat": "{{instance}}: {{path}} OFFLINE"
    },
    {
     "expr": "(doris_be_disks_state{job=\"$cluster_name\"} == 1)+0",
     "legendFormat": "{{instance}}: {{path}} ONLINE"
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "cluster_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "[$cluster_name] FE Node",
   "type": "stat",
   "description": "Total Frontends node number",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{group=\"fe\", job=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "[$cluster_name]  FE Alive",
   "type": "stat",
   "description": "Total alive number of Frontends. Normally, it should be equal to the Total number of Frontends",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{group=\"fe\", job=\"$cluster_name\"}==1)"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE Node",
   "type": "stat",
   "description": "Total Backends node number",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{group=\"be\", job=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE Alive",
   "type": "stat",
   "description": "Total alive number of Backends. Normally, it should be equal to the Total number of Backends.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{group=\"be\", job=\"$cluster_name\"}==1)"
    }
   ]
  },
  {
   "title": "[$cluster_name] Used Capacity",
   "type": "stat",
   "description": "Total used disk capacity of all Backends.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(doris_be_disks_data_used_capacity{job=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "[$cluster_name] Total Capacity",
   "type": "stat",
   "description": "Total disk capacity of all Backends",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(doris_be_disks_total_capacity{job=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "[$cluster_name] Max Replayed journal id",
   "type": "graph",
   "description": "The max replayed meta data journal id on Frontends.\nNormally, all Frontends should be same on this metrics, or just slightly different for a short period.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "doris_fe_max_journal_id{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Image counter",
   "type": "graph",
   "description": "The counter of meta data image generation on Master Frontend. And the counter of image successfully pushing to other Non-master Frontends.\nThese metrics is expected to increase at reasonable intervals. And normally, they should be equal.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "doris_fe_image_write{job=\"$cluster_name\", instance=\"$fe_master\"}",
     "legendFormat": "{{instance}}-generate"
    },
    {
     "expr": "doris_fe_image_push{job=\"$cluster_name\", instance=\"$fe_master\"}",
     "legendFormat": "{{instance}}-push"
    }
   ]
  },
  {
   "title": "[$cluster_name] BDBJE Write",
   "type": "graph",
   "description": "The left Y axes shows write latency of 99th. The right Y axes shows the write per seconds of journal.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "doris_fe_editlog_write_latency_ms{job=\"$cluster_name\", instance=\"$fe_master\",quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-99th"
    },
    {
     "expr": "rate(doris_fe_edit_log_write{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
     "legendFormat": "{{instance}}-rate"
    }
   ]
  },
  {
   "title": "[$cluster_name] Scheduling Tablets",
   "type": "graph",
   "description": "Number of tablets begin scheduled. These tablet may be in recovery process or balance process",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "doris_fe_scheduled_tablet_num{job=\"$cluster_name\", instance=\"$fe_master\"}",
     "legendFormat": "Scheduling tablet number"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE IO Util",
   "type": "graph",
   "description": "The max IO util of each Backend",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "doris_be_max_disk_io_util_percent{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE Compaction Score",
   "type": "graph",
   "description": "The compaction score of each BE",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "doris_fe_tablet_max_compaction_score{job=\"$cluster_name\", instance=\"$fe_master\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "[$cluster_name] RPS",
     "type": "graph",
     "description": "Requests per seconds on each Frontends.\nRequests include all requests sending to the Frontends.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(doris_fe_request_total{job=\"$cluster_name\", group=\"fe\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] QPS",
     "type": "graph",
     "description": "Queries per seconds on each Frontends.\nQueries only include Select requests.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(doris_fe_query_total{job=\"$cluster_name\", group=\"fe\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] 99th Latency",
     "type": "graph",
     "description": "99 quantiles of query latency on each Frontends.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(doris_fe_query_latency_ms{job=\"$cluster_name\", quantile=\"0.99\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] Query Percentile",
     "type": "graph",
     "description": "Left Y axes indicates 95 to 99 quantiles of query latency on each Frontends.\nRight Y axes indicates the query rate per 1 min.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "doris_fe_query_latency_ms{job=\"$cluster_name\", instance=\"$fe_instance\"}",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "rate(doris_fe_query_latency_ms_count{job=\"$cluster_name\", instance=\"$fe_instance\"}[1m])",
       "legendFormat": "query rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] Query Error [1m]",
     "type": "graph",
     "description": "Left Y axes indicates the accumulated  error queries number.\nRight Y axes indicates the error query rate per 1 min.\nNormally, the error query rate should be 0.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_fe_query_err{job=\"$cluster_name\"}",
       "legendFormat": "Err Counter-{{instance}}"
      },
      {
       "expr": "rate(doris_fe_query_err{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "Err Rate-{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Connections",
     "type": "graph",
     "description": "The connections' number to each Frontends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_fe_connection_total{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "[$cluster_name] Mini Load Job",
     "type": "table-old",
     "description": "Statistic of Mini load jobs's num in each Load State.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"MINI\", instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Hadoop Load Job",
     "type": "table-old",
     "description": "Statistic of Hadoop load jobs's num in each Load State.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"HADOOP\", instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Broker Load Job",
     "type": "table-old",
     "description": "Statistic of Broker load jobs's num in each Load State.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Insert Load Job",
     "type": "table-old",
     "description": "Statistic of load jobs's num  in each Load State which is generated by Insert Stmt.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Mini load tendency",
     "type": "graph",
     "description": "The trend report of mini load job",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"MINI\", instance=\"$fe_master\", state=\"PENDING\"}",
       "legendFormat": "PENDING"
      },
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"MINI\", instance=\"$fe_master\", state=\"ETL\"}",
       "legendFormat": "ETL"
      },
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"MINI\", instance=\"$fe_master\", state=\"LOADING\"}",
       "legendFormat": "LOADING"
      }
     ]
    },
    {
     "title": "[$cluster_name] Hadoop load tendency",
     "type": "graph",
     "description": "The trend report of hadoop load job",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"HADOOP\", instance=\"$fe_master\", state=\"PENDING\"}",
       "legendFormat": "PENDING"
      },
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"HADOOP\", instance=\"$fe_master\", state=\"ETL\"}",
       "legendFormat": "ETL"
      },
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"HADOOP\", instance=\"$fe_master\", state=\"LOADING\"}",
       "legendFormat": "LOADING"
      }
     ]
    },
    {
     "title": "[$cluster_name] Broker load tendency",
     "type": "graph",
     "description": "The trend report of broker load job",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"PENDING\"}",
       "legendFormat": "PENDING"
      },
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"ETL\"}",
       "legendFormat": "ETL"
      },
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"LOADING\"}",
       "legendFormat": "LOADING"
      }
     ]
    },
    {
     "title": "[$cluster_name] Insert load tendency",
     "type": "graph",
     "description": "The trend report of insert load job",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"PENDING\"}",
       "legendFormat": "PENDING"
      },
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"ETL\"}",
       "legendFormat": "ETL"
      },
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"LOADING\"}",
       "legendFormat": "LOADING"
      }
     ]
    },
    {
     "title": "[$cluster_name] Load submit",
     "type": "graph",
     "description": "Show the counter of Load job submitted and Load job finished.\nThe two lines show be paralleled if the load submit is a routine operations.\nRight Y axes shows the submit rate of load job",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_fe_load_add{instance=\"$fe_master\"}",
       "legendFormat": "{{instance}}-Submit"
      },
      {
       "expr": "doris_fe_load_finished{instance=\"$fe_master\"}",
       "legendFormat": "{{instance}}-Finished"
      },
      {
       "expr": "rate(doris_fe_load_add{instance=\"$fe_master\"}[1h])",
       "legendFormat": "{{instance}}-Submit rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] SC Job",
     "type": "table-old",
     "description": "Number of running schema change jobs.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 56 },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", instance=\"$fe_master\", type=\"SCHEMA_CHANGE\"}",
       "legendFormat": "asds"
      }
     ]
    },
    {
     "title": "[$cluster_name] Report queue size",
     "type": "graph",
     "description": "Queue size of report in Master FE.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_fe_report_queue_size{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "Report queue size"
      }
     ]
    },
    {
     "title": "[$cluster_name] Rollup Job",
     "type": "table-old",
     "description": "Number of running rollup jobs.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 59 },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"$cluster_name\", instance=\"$fe_master\", type=\"ROLLUP\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "[$cluster_name] Txn Begin/Success on FE",
     "type": "graph",
     "description": "Show the number and rate of txn begin and success",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "doris_fe_txn_begin{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "txn begin"
      },
      {
       "expr": "doris_fe_txn_success{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "txn success"
      },
      {
       "expr": "irate(doris_fe_txn_begin{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "txn begin rate"
      },
      {
       "expr": "irate(doris_fe_txn_success{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "txn success rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] Txn Failed/Reject on FE",
     "type": "graph",
     "description": "Show the failed txn request. Including rejected request and failed txn",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(doris_fe_txn_reject{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "txn reject rate"
      },
      {
       "expr": "rate(doris_fe_txn_failed{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "txn failed rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] Publish Task on BE",
     "type": "graph",
     "description": "The number of total publish task request and error rate.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"publish\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"publish\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Txn Requset on BE",
     "type": "graph",
     "description": "Show the txn request on BE",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(doris_be_txn_request{group=\"be\", job=\"$cluster_name\", type=\"begin\"})",
       "legendFormat": "begin"
      },
      {
       "expr": "sum(doris_be_txn_request{group=\"be\", job=\"$cluster_name\", type=\"exec\"})",
       "legendFormat": "exec"
      },
      {
       "expr": "sum(doris_be_txn_request{group=\"be\", job=\"$cluster_name\", type=\"commit\"})",
       "legendFormat": "commit"
      },
      {
       "expr": "sum(doris_be_txn_request{group=\"be\", job=\"$cluster_name\", type=\"rollback\"})",
       "legendFormat": "rollback"
      }
     ]
    },
    {
     "title": "[$cluster_name] Txn Load Bytes/Rows rate",
     "type": "graph",
     "description": "Left Y axes indicates the total received bytes rate of txn. Right Y axes indicates the loaded rows rate of txn.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(doris_be_stream_load{group=\"be\", job=\"$cluster_name\", type=\"receive_bytes\"}[$interval]))",
       "legendFormat": "bytes"
      },
      {
       "expr": "sum(rate(doris_be_stream_load{group=\"be\", job=\"$cluster_name\", type=\"load_rows\"}[$interval]))",
       "legendFormat": "rows"
      }
     ]
    }
   ]
  },
  {
   "title": "FE JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "[$cluster_name] [$fe_instance] JVM Heap",
     "type": "graph",
     "description": "JVM Heap usage of specified Frontend.\nLeft Y Axes shows the used/max heap size.\nRight Y Axes shows the used percentage.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"used\"}) * 100 / sum(jvm_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"max\"})",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Non Heap",
     "type": "graph",
     "description": "JVM Non Heap usage of specified Frontend.\nLeft Y Axes shows the used/committed non heap size.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_non_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_non_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"committed\"}",
       "legendFormat": "committed"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Direct Buffer",
     "type": "graph",
     "description": "JVM Direct buffer usage of specified Frontend.\nLeft Y Axes shows the used/capacity direct buffer size.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_direct_buffer_pool_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_direct_buffer_pool_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"capacity\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "[$cluster_name] JVM Threads",
     "type": "graph",
     "description": "Num of threads of FE JVM",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_thread{job=\"$cluster_name\", group=\"fe\", type=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Young",
     "type": "graph",
     "description": "JVM young generation usage of specified Frontend.\nLeft Y Axes shows the used/max young generation size.\nRight Y Axes shows the used percentage.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_young_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_young_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_young_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"used\"}) * 100 / sum(jvm_young_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"max\"})",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Old",
     "type": "graph",
     "description": "JVM old generation usage of specified Frontend. Left Y Axes shows the used/max old generation size. Right Y Axes shows the used percentage.\nNormally, the usage percentage should be less than 80%.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_old_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_old_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_old_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"used\"}) * 100 / sum(jvm_old_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"max\"})",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Young GC",
     "type": "graph",
     "description": "JVM young gc stat of specified Frontend. \nLeft Y Axes shows times of young gc.\nRight Y Axes shows the time cost of each young gc.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_young_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"count\"}",
       "legendFormat": "count"
      },
      {
       "expr": "sum(jvm_young_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"time\"}) / sum(jvm_young_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"count\"})",
       "legendFormat": "avg time"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Old GC",
     "type": "graph",
     "description": "JVM full gc stat of specified Frontend. \nLeft Y Axes shows times of full gc.\nRight Y Axes shows the time cost of each full gc.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_old_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"count\"}",
       "legendFormat": "count"
      },
      {
       "expr": "sum(jvm_old_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"time\"}) / sum(jvm_old_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"count\"})",
       "legendFormat": "avg time"
      }
     ]
    }
   ]
  },
  {
   "title": "BE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "[$cluster_name] BE CPU Idle",
     "type": "graph",
     "description": "CPU idle stat of Backends.\nLow means CPU is busy.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(doris_be_cpu{mode=\"idle\", job=\"$cluster_name\"}[$interval])) by (job, instance)) / (sum(rate(doris_be_cpu{job=\"$cluster_name\"}[$interval])) by (job, instance)) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Mem",
     "type": "graph",
     "description": "Memory usage of Backends.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "doris_be_memory_allocated_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Net send/receive bytes",
     "type": "graph",
     "description": "Network send(Left Y)/receive(Right Y) bytes rate of all device except 'lo'",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(doris_be_network_send_bytes{job=\"$cluster_name\", group=\"be\", device!=\"lo\"}[$interval])",
       "legendFormat": "{{instance}}-{{device}}-send"
      },
      {
       "expr": "irate(doris_be_network_receive_bytes{job=\"$cluster_name\", group=\"be\", device!=\"lo\"}[$interval])",
       "legendFormat": "{{instance}}-{{device}}-receive"
      }
     ]
    },
    {
     "title": "[$cluster_name] Disk Usage",
     "type": "graph",
     "description": "Disk capacity usage of Backends",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(SUM(doris_be_disks_total_capacity{job=\"$cluster_name\"}) by (instance, path) - SUM(doris_be_disks_avail_capacity{job=\"$cluster_name\"}) by (instance, path)) / SUM(doris_be_disks_total_capacity{job=\"$cluster_name\"}) by (instance, path)",
       "legendFormat": "{{instance}}:{{path}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Tablet Distribution",
     "type": "graph",
     "description": "Number of tablets of each Backends",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "doris_fe_tablet_num{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE FD count",
     "type": "graph",
     "description": "The file descriptor usage of Backends. Left Y axes shows the used fd num. Right Y axes shows the soft limit open file number.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_be_process_fd_num_used{job=\"$cluster_name\", group=\"be\"}",
       "legendFormat": "{{instance}}-used"
      },
      {
       "expr": "doris_be_process_fd_num_limit_soft{job=\"$cluster_name\", group=\"be\"}",
       "legendFormat": "{{instance}}-soft limit"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE thread num",
     "type": "graph",
     "description": "The thread number of Backends",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_be_process_thread_num{job=\"$cluster_name\", group=\"be\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Disk IO util",
     "type": "graph",
     "description": "IO util of Backends.\nHigh means I/O is busy.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "doris_be_max_disk_io_util_percent",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Compaction Base",
     "type": "graph",
     "description": "Base compaction rate of Backends.\nNormally, base compaction only runs between 20:00 to 4:00 and it is configurable.\nRight Y axes indicates the total base compaction bytes.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(doris_be_compaction_bytes_total{type=\"base\", job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(doris_be_compaction_bytes_total{type=\"base\", job=\"$cluster_name\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Compaction Cumulate",
     "type": "graph",
     "description": "Cumulative compaction rate of Backends.\nRight Y axes indicates the total cumulative compaction bytes.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(doris_be_compaction_bytes_total{type=\"cumulative\", job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "SUM(doris_be_compaction_bytes_total{type=\"cumulative\", job=\"$cluster_name\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Push Bytes",
     "type": "graph",
     "description": "Loading rate of Backends.\nThis indicates the rate of file downloading in LOADING state of load job(MINI and BROKER load).\nRight Y axes indicates the total rate of file downloading.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(doris_be_push_request_write_bytes{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(doris_be_push_request_write_bytes{job=\"$cluster_name\"}[$interval]))",
       "legendFormat": "Total rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Push Rows",
     "type": "graph",
     "description": "Loading rows rate of Backends.\nThis indicates the rate of rows loaded in LOADING state of load job. Right Y axes shows the total push rate of cluster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(doris_be_push_request_write_rows{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(doris_be_push_request_write_rows{job=\"$cluster_name\"}[$interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Scan Bytes",
     "type": "graph",
     "description": "Scan rate of Backends.\nThis indicates the read rate when processing queries.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(doris_be_query_scan_bytes{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "[$cluster_name] BE Scan Rows",
     "type": "graph",
     "description": "Scan rows rate of Backends.\nThis indicates the read rows rate when processing queries.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(doris_be_query_scan_rows{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Tablet Meta Write",
     "type": "graph",
     "description": "Left Y axes shows the write rate of tablet header saved in rocksdb. Right Y axes shows the duration of each write operation.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "irate(doris_be_meta_request_total{job=\"$cluster_name\", type=\"write\"}[$interval])",
       "legendFormat": "{{instance}}-rate"
      },
      {
       "expr": "doris_be_meta_request_duration{job=\"$cluster_name\", type=\"write\"} / doris_be_meta_request_total{job=\"$cluster_name\", type=\"write\"}",
       "legendFormat": "{{instance}}-latency"
      }
     ]
    },
    {
     "title": "[$cluster_name] Tablet Meta Read",
     "type": "graph",
     "description": "Left Y axes shows the read rate of tablet header saved in rocksdb. Right Y axes shows the duration of each read operation.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "irate(doris_be_meta_request_total{job=\"$cluster_name\", type=\"read\"}[$interval])",
       "legendFormat": "{{instance}}-rate"
      },
      {
       "expr": "doris_be_meta_request_duration{job=\"$cluster_name\", type=\"read\"} / doris_be_meta_request_total{job=\"$cluster_name\", type=\"read\"}",
       "legendFormat": "{{instance}}-latency"
      }
     ]
    }
   ]
  },
  {
   "title": "BE tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "[$cluster_name] Tablets Report",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"report_all_tablets\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"report_all_tablets\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Single Tablet Report",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"report_tablet\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"report_tablet\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Finish task report",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"finish_task\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"finish_task\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Push Task",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(doris_be_push_requests_total{job=\"$cluster_name\", status=\"SUCCESS\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_push_requests_total{job=\"$cluster_name\", status=\"FAIL\"}[$interval])",
       "legendFormat": "{{instance}}-failed"
      }
     ]
    },
    {
     "title": "[$cluster_name] Push Task Cost Time",
     "type": "graph",
     "description": "The average cost time of push tasks on each Backend.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(doris_be_push_request_duration_us{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Delete",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"delete\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"delete\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Base Compaction",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"base_compaction\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"base_compaction\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Cumulative Compaction",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"cumulative_compaction\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"cumulative_compaction\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Clone",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"clone\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"clone\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Create rollup",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"create_rollup\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"create_rollup\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Schema change",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"schema_change\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"schema_change\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Create tablet",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"create_tablet\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{job=\"$cluster_name\", type=\"create_tablet\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}