{
 "title": "HBase",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "regionserver",
    "label": "RegionServer",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"regionserver\"},instance)"
    }
   },
   {
    "name": "master",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"hbasemaster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HMaster启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"hbasemaster\",instance=\"$master\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (hadoop_hbase_masterstarttime{job=\"hbasemaster\",instance=\"$master\"}/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HMaster堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_memheapmaxm{job=\"hbasemaster\",instance=\"$master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RegionServer堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_memheapmaxm{job=\"regionserver\",instance=\"$regionserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线RegionServer数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_numregionservers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HMaster堆内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hadoop_hbase_memheapusedm{job=\"hbasemaster\"}/hadoop_hbase_memheapmaxm{job=\"hbasemaster\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "正在转换的区域数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_ritcount{instance=\"$master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "转换区域超过阀值时间的数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_ritcountoverthreshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "日志报错数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(hadoop_hbase_logerror)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "离线RegionServer数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_numdeadregionservers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HMaster负载",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "hadoop_hbase_averageload", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "RegionServer刷新时间",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(hadoop_hbase_flushtime_mean[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hbase LogFile大小",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "hadoop_hbase_hlogfilesize", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Hbase刷新速率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(hadoop_hbase_flushedcellssize[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}