{
 "title": "HDFS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namenode",
    "label": "namenode",
    "query": {
     "query": "label_values(process_start_time_seconds{job='namenode'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NameNode启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"namenode\",instance=\"$namenode\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NameNode运行时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"namenode\",instance=\"$namenode\"}"
    }
   ]
  },
  {
   "title": "HDFS容量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_DataNode_Capacity{name=\"FSDatasetState\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线DataNode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_NumLiveDataNodes{name=\"FSNamesystem\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "离线DataNode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_NumDeadDataNodes{name=\"FSNamesystem\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NameNode堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_MemHeapMaxM{instance=\"$namenode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDFS文件总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_TotalFileOps{name=\"NameNodeActivity\",job=\"namenode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDFS已用量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_DataNode_DfsUsed{name=\"FSDatasetState\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "非HDFS使用存储",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_NonDfsUsedSpace{job=\"namenode\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "等待备份的block个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_PendingReplicationBlocks{name=\"FSNamesystem\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "心跳超时数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_ExpiredHeartbeats{job=\"namenode\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NameNode堆内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(Hadoop_NameNode_MemHeapUsedM/Hadoop_NameNode_MemHeapMaxM )*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "等待删除block个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_PendingDeletionBlocks{name=\"FSNamesystem\",job=\"namenode\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "block总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_BlocksTotal{name=\"FSNamesystem\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DataNode存储使用率",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort(Hadoop_DataNode_DfsUsed{name=\"FSDatasetState\"}*100/ Hadoop_DataNode_Capacity{name=\"FSDatasetState\"})",
     "legendFormat": "broker"
    }
   ]
  },
  {
   "title": "DataNode堆内存使用率",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(Hadoop_DataNode_MemHeapUsedM{job=\"datanode\"}/ Hadoop_DataNode_MemHeapMaxM{job=\"datanode\"})*100",
     "legendFormat": "broker"
    }
   ]
  },
  {
   "title": "HDFS读写速率",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(Hadoop_DataNode_BytesRead[5m]))",
     "legendFormat": "读取速率"
    },
    {
     "expr": "sum(rate(Hadoop_DataNode_BytesWritten[5m]))",
     "legendFormat": "写入速率"
    }
   ]
  },
  {
   "title": "写入block的次数",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "Hadoop_NameNode_AddBlockNumOps", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GC耗时",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "Hadoop_NameNode_GcTimeMillis", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "NameNode创建、删除文件次数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_FilesCreated)",
     "legendFormat": "创建文件"
    },
    {
     "expr": "sum(Hadoop_NameNode_FilesDeleted)",
     "legendFormat": "删除文件"
    }
   ]
  }
 ]
}