{
 "title": "Spark",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"spark\"},instance)"
    }
   },
   {
    "name": "env",
    "label": "surroundings",
    "query": {
     "query": "label_values(process_start_time_seconds,env)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "可用的Worker数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "master_aliveWorkers{job=\"spark\"}"
    }
   ]
  },
  {
   "title": "executors总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(worker_executors)" }
   ]
  },
  {
   "title": "等待的app数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "master_waitingApps{job=\"spark\"}"
    }
   ]
  },
  {
   "title": "worker内存总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_memFree_MB{job=\"spark\"})+sum(worker_memUsed_MB{job=\"spark\"})"
    }
   ]
  },
  {
   "title": "SparkStreaming完成任务数",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "spark_app_executor_tasks{job=\"spark\",qty=\"completeTasks\"}"
    }
   ]
  },
  {
   "title": "JVM使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_heap_used{job=\"spark\"})/(sum(jvm_heap_used{job=\"spark\"})+sum(jvm_heap_committed{job=\"spark\"}))*100"
    }
   ]
  },
  {
   "title": "Spark的app数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "master_apps{job=\"spark\"}"
    }
   ]
  },
  {
   "title": "Core总量使用情况",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_coresUsed{job=\"spark\"})/(sum(worker_coresUsed{job=\"spark\"})+sum(worker_coresFree{job=\"spark\"}))"
    }
   ]
  },
  {
   "title": "worker内存剩余量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_memFree_MB{job=\"spark\"})"
    }
   ]
  },
  {
   "title": "sparkstreaming活跃的任务数数",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "spark_app_executor_tasks{job=\"spark\",qty=\"activeTasks\"}"
    }
   ]
  },
  {
   "title": "worker的已使用的core的总数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_coresUsed{job=\"spark\"})"
    }
   ]
  },
  {
   "title": "worker内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_memUsed_MB{job=\"spark\"})/(sum(worker_memFree_MB{job=\"spark\"})+sum(worker_memUsed_MB{job=\"spark\"}))*10"
    }
   ]
  },
  {
   "title": "Worker Cores总剩余量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_coresFree{job=\"spark\"})"
    }
   ]
  },
  {
   "title": "worker内存使用总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_memUsed_MB{job=\"spark\"})"
    }
   ]
  },
  {
   "title": "app_jvm内存使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "spark_app_jvm_memory_usage{mem_type=\"heap\",qty=\"usage\"}",
     "legendFormat": "{{instance}},应用号:{{application}} ,所属节点：{{executor_id}}"
    }
   ]
  },
  {
   "title": "spark_app_block_manager情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_app_block_manager{job=\"spark\"}",
     "legendFormat": "{{instance}}  类型：{{qty}}"
    }
   ]
  },
  {
   "title": "JVM使用情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_total_used{job=\"spark\"}",
     "legendFormat": "{{instance}} JVM使用量"
    }
   ]
  },
  {
   "title": "app_dag消息处理情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_app_dag_scheduler{qty=\"m15_rate\"}",
     "legendFormat": "{{instance}}  15分钟消息处理量"
    },
    {
     "expr": "spark_app_dag_scheduler{qty=\"m5_rate\"}",
     "legendFormat": "{{instance}}  5分钟消息处理量"
    },
    {
     "expr": "spark_app_dag_scheduler{qty=\"m1_rate\"}",
     "legendFormat": "{{instance}}  1分钟消息处理量"
    }
   ]
  },
  {
   "title": "app批数据数量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_app_streaming_metrics{qty=\"waitingBatches\",type=\"streaming\"}",
     "legendFormat": "app流状态为等待中的批数量"
    },
    {
     "expr": "spark_app_streaming_metrics{qty=\"runningBatches\",type=\"streaming\"}",
     "legendFormat": "app流状态为运行的批数量"
    },
    {
     "expr": "spark_app_streaming_metrics{qty=\"totalCompletedBatches\",type=\"streaming\"}",
     "legendFormat": "app流完成的批总数"
    },
    {
     "expr": "spark_app_streaming_metrics{qty=\"unprocessedBatches\",type=\"streaming\"}",
     "legendFormat": "app流未处理批数量"
    }
   ]
  },
  {
   "title": "各节点Core使用量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "worker_coresUsed{job=\"spark\"}",
     "legendFormat": "{{instance}}节点core使用量"
    }
   ]
  },
  {
   "title": "JVM CodeCache使用情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_pools_Code_Cache_used{job=\"spark\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}jvm缓存使用情况"
    }
   ]
  },
  {
   "title": "worker内存使用情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "worker_memUsed_MB{job=\"spark\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}内存使用量"
    }
   ]
  },
  {
   "title": "spark app hdfs文件系统的读写量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(spark_app_filesystem_usage{fs_type=\"hdfs\",qty=\"write_bytes\",instance=~\"$node\"})",
     "legendFormat": "hdfs写字节量"
    },
    {
     "expr": "sum(spark_app_filesystem_usage{fs_type=\"hdfs\",qty=\"read_bytes\",instance=~\"$node\"})",
     "legendFormat": "hdfs读字节量"
    }
   ]
  }
 ]
}