{
 "title": "YARN",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resourcemanager",
    "label": "RM",
    "query": {
     "query": "label_values(process_start_time_seconds{job='resourcemanager'},instance)"
    }
   },
   {
    "name": "queue",
    "label": "队列",
    "query": {
     "query": "label_values(Hadoop_ResourceManager_AvailableMB{q1!=\"default\"},q1)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ResourceManager启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"resourcemanager\",instance=\"$resourcemanager\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ResourceManager在线时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"resourcemanager\",instance=\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yarn虚拟内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AvailableMB{name=\"QueueMetrics\",q0=\"root\",job=\"resourcemanager\",q1=\"\",user=\"\"}/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "虚拟核数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_FairShareVCores{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1=\"\",user=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ResourceManager堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(Hadoop_ResourceManager_MemHeapMaxM)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeManager在线数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_NumActiveNMs)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeManager离线数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_NumLostNMs)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "application提交数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsSubmitted{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1=\"\",user=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "正在运行的application数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsRunning{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1=\"\",user=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 已分配的container数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedContainers{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1 =\"\",user=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "application完成数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsCompleted{q0=\"root\",q1=\"\",user=\"\",name=\"QueueMetrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ResourceManager堆内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_MemHeapUsedM *100/ Hadoop_ResourceManager_MemHeapMaxM",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "等待处理的资源",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_PendingMB{q0=\"root\",q1=\"\",user=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yarn内核使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedVCores{name=\"QueueMetrics\",q0=\"root\",job=\"resourcemanager\",q1=\"\",user=\"\"})/sum(Hadoop_ResourceManager_AvailableVCores{name=\"QueueMetrics\",q0=\"root\",job=\"resourcemanager\",q1=\"\",user=\"\"})*100"
    }
   ]
  },
  {
   "title": "Yarn内存使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedMB{name=\"QueueMetrics\",q0=\"root\",job=\"resourcemanager\",q1=\"\",user=\"\"})/sum(Hadoop_ResourceManager_AvailableMB{name=\"QueueMetrics\",q0=\"root\",job=\"resourcemanager\",q1=\"\",user=\"\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "等待资源的application数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsPending{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1=\"\",user=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yarn队列内存分配资源占比",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_MaxShareMB{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1!=\"default\",q1!=\"\"}/2) by (q1)",
     "legendFormat": "{{q1}}"
    }
   ]
  },
  {
   "title": "Yarn队列分配核数占比",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_MaxShareVCores{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1!=\"default\",q1!=\"\"}/2) by (q1)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Yarn队列内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(Hadoop_ResourceManager_AllocatedMB{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1!=\"default\",q1!=\"\"}/2) by (q1) )*100/sum(Hadoop_ResourceManager_MaxShareMB{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1!=\"default\",q1!=\"\"}/2) by (q1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Yarn队列内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedMB{q1!=\"\",q1!=\"default\", user=\"\",name=\"QueueMetrics\"}) by (q1)",
     "legendFormat": "{{q1}}已用内存"
    }
   ]
  },
  {
   "title": "队列中正在运行的App数",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_AppsRunning{job=\"resourcemanager\",name=\"QueueMetrics\",instance=\"$resourcemanager\",q0=\"root\",q1!=\"\",user=\"\"}",
     "legendFormat": "{{q1}}"
    }
   ]
  },
  {
   "title": "ResourceManager Gc时间",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_GcTimeMillis",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC心跳时间",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_RpcQueueTimeAvgTime",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}