USE test;
DROP TABLE IF EXISTS alter_00147;
CREATE TABLE alter_00147 (d Date DEFAULT toDate('2015-01-01'), n Nested(x String)) ENGINE = CnchMergeTree
PARTITION BY d ORDER BY d SETTINGS index_granularity = 8192;
INSERT INTO alter_00147 (`n.x`) VALUES (['Hello', 'World']);
SELECT * FROM alter_00147 order by n.x;
SELECT * FROM alter_00147 ARRAY JOIN n order by n.x;
SELECT * FROM alter_00147 ARRAY JOIN n WHERE n.x LIKE '%Hello%';
ALTER TABLE alter_00147 ADD COLUMN n.y Array(UInt64);
SELECT * FROM alter_00147 order by n.x;
SELECT * FROM alter_00147 ARRAY JOIN n order by n.x;
SELECT * FROM alter_00147 ARRAY JOIN n WHERE n.x LIKE '%Hello%';
INSERT INTO alter_00147 (`n.x`) VALUES (['Hello2', 'World2']);
SELECT * FROM alter_00147 ORDER BY n.x;
SELECT * FROM alter_00147 ARRAY JOIN n ORDER BY n.x;
SELECT * FROM alter_00147 ARRAY JOIN n WHERE n.x LIKE '%Hello%' ORDER BY n.x;
SYSTEM START MERGES test.alter_00147;
SELECT sleep(3) FORMAT Null;
OPTIMIZE TABLE test.alter_00147;
SELECT * FROM alter_00147 ORDER BY n.x;
SELECT * FROM alter_00147 ARRAY JOIN n order by n.x;
SELECT * FROM alter_00147 ARRAY JOIN n WHERE n.x LIKE '%Hello%' ORDER BY n.x;
DROP TABLE alter_00147;
