USE test;
DROP TABLE IF EXISTS nested;
CREATE TABLE nested (x UInt8, n Nested(a UInt64, b String)) ENGINE = CnchMergeTree ORDER BY x;
INSERT INTO nested VALUES (1, [2, 3], ['Hello', 'World']);
INSERT INTO nested VALUES (4, [5], ['Goodbye']);
SELECT * FROM nested ORDER BY x;
SELECT x, n.a FROM nested ORDER BY x;
SELECT n.a, n.b FROM nested ORDER BY n.a;
DROP TABLE IF EXISTS nested;
CREATE TABLE nested (x UInt8, n Nested(a UInt64, b String)) ENGINE = CnchMergeTree ORDER BY x;
INSERT INTO nested VALUES (1, [2, 3], ['Hello', 'World']);
INSERT INTO nested VALUES (4, [5], ['Goodbye']);
SELECT * FROM nested ORDER BY x;
SELECT x, n.a FROM nested ORDER BY x;
SELECT n.a, n.b FROM nested ORDER BY n.a;
DROP TABLE IF EXISTS nested;
CREATE TABLE nested (x UInt8, n Nested(a UInt64, b String)) ENGINE = CnchMergeTree ORDER BY x;
INSERT INTO nested VALUES (1, [2, 3], ['Hello', 'World']);
INSERT INTO nested VALUES (4, [5], ['Goodbye']);
SELECT * FROM nested ORDER BY x;
SELECT x, n.a FROM nested ORDER BY x;
SELECT n.a, n.b FROM nested ORDER BY n.a;
DROP TABLE IF EXISTS nested;
CREATE TABLE nested (x UInt8, n Nested(a UInt64, b String)) ENGINE = CnchMergeTree ORDER BY x;
INSERT INTO nested VALUES (1, [2, 3], ['Hello', 'World']);
INSERT INTO nested VALUES (4, [5], ['Goodbye']);
SELECT * FROM nested ORDER BY x;
SELECT x, n.a FROM nested ORDER BY x;
SELECT n.a, n.b FROM nested ORDER BY n.a;
DROP TABLE IF EXISTS nested;
CREATE TABLE nested (x UInt8, n Nested(a UInt64, b String)) ENGINE = CnchMergeTree ORDER BY x;
INSERT INTO nested VALUES (1, [2, 3], ['Hello', 'World']);
INSERT INTO nested VALUES (4, [5], ['Goodbye']);
SELECT * FROM nested ORDER BY x;
SELECT x, n.a FROM nested ORDER BY x;
SELECT n.a, n.b FROM nested ORDER BY n.a;
DROP TABLE nested;
