import groovy.json.JsonOutput

def PROJECT_NAME = (env.JOB_NAME.tokenize('/') as String[])[0]
def BRANCH = env.BRANCH_NAME
def REPO = scm.getUserRemoteConfigs()[0].getUrl()
def TEST_RESULT

pipeline {
    options {
        disableConcurrentBuilds()
    }
    triggers {
        pollSCM('*/2 * * * *')
        cron('0 */7 * * *')
    }
    environment {
        IMAGE_PREFIX = "reg.docker.alibaba-inc.com/abm-aone/paas-nacos"
    }
    agent any
    parameters {
        string(name: 'MAVEN_X86_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-aone/maven', description: '')
        string(name: 'MAVEN_ARM_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-arm64v8/maven', description: '')
        string(name: 'JRE8_X86_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-aone/openjdk8-jre', description: '')
        string(name: 'JRE8_ARM_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-arm64v8/openjdk8-jre', description: '')
        string(name: 'PYTHON2_X86_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-aone/python27', description: '')
        string(name: 'PYTHON2_ARM_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-arm64v8/python27', description: '')
        string(name: 'ALPINE_X86_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/alibaba_apsara_paas/alpine:v1.0.0', description: '')
        string(name: 'ALPINE_ARM_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-aone/arm-alpine', description: '')
        string(name: 'MIGRATE_X86_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-aone/migrate', description: '')
        string(name: 'MIGRATE_ARM_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-arm64v8/migrate', description: '')
        string(name: 'X86_IMAGE_PREFIX', defaultValue: 'reg.docker.alibaba-inc.com/abm-aone/paas-nacos', description: '')
        string(name: 'ARM_IMAGE_PREFIX', defaultValue: 'reg.docker.alibaba-inc.com/abm-arm64v8/paas-nacos', description: '')
    }
    stages {
        stage("Clone Repo") {
            steps {
                git credentialsId: "$GIT_CREDENTIAL",
                    url: REPO,
                    branch: BRANCH
            }
        }
        stage("Build & Push Images") {
            agent any
            steps {
                parallel (
                    'x86': {
                        script {
                            retry(count: "${env.MAX_RETRY_COUNT}") {
                                sh "bash -c 'MAVEN_IMAGE=${params.MAVEN_X86_IMAGE} JRE8_IMAGE=${params.JRE8_X86_IMAGE}  envsubst \"\\\$MAVEN_IMAGE \\\$JRE8_IMAGE\" < Dockerfile.tpl > Dockerfile'"
                                x86AppImage = docker.build("${params.X86_IMAGE_PREFIX}:$BRANCH", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile .")
                                docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) { x86AppImage.push()}

                                sh "bash -c 'MIGRATE_IMAGE=${params.MIGRATE_X86_IMAGE} envsubst \"\\\$MIGRATE_IMAGE\" < Dockerfile_db_migration.tpl > Dockerfile_db_migration'"
                                x86DbImage = docker.build("${params.X86_IMAGE_PREFIX}-db-migration:$BRANCH", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile_db_migration .")
                                docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) { x86DbImage.push() }

                                sh "bash -c 'PYTHON2_IMAGE=${params.PYTHON2_X86_IMAGE} envsubst \"\\\$PYTHON2_IMAGE\" < Dockerfile_config_init.tpl > Dockerfile_config_init'"
                                x86ConfigInitImage = docker.build("${params.X86_IMAGE_PREFIX}-config-init:$BRANCH", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile_config_init .")
                                docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) { x86ConfigInitImage.push()}

                                sh "bash -c 'ALPINE_IMAGE=${params.ALPINE_X86_IMAGE} envsubst \"\\\$ALPINE_IMAGE\" < Dockerfile_config_readiness.tpl > Dockerfile_config_readiness'"
                                x86ConfigReadinessImage = docker.build("${params.X86_IMAGE_PREFIX}-config-readiness:$BRANCH", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile_config_readiness .")
                                docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) { x86ConfigReadinessImage.push()}
                            }
                        }
                    },
                    'arm': {
                        script {
                            retry(count: "${env.MAX_RETRY_COUNT}") {
                                sh "bash -c 'MAVEN_IMAGE=${params.MAVEN_ARM_IMAGE} JRE8_IMAGE=${params.JRE8_ARM_IMAGE}  envsubst \"\\\$MAVEN_IMAGE \\\$JRE8_IMAGE\" < Dockerfile.tpl > Dockerfile.arm64v8'"
                                armAppImage = docker.build("${params.ARM_IMAGE_PREFIX}:$BRANCH", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile.arm64v8 .")
                                docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) { armAppImage.push()}

                                sh "bash -c 'MIGRATE_IMAGE=${params.MIGRATE_ARM_IMAGE} envsubst \"\\\$MIGRATE_IMAGE\" < Dockerfile_db_migration.tpl > Dockerfile_db_migration.arm64v8'"
                                armDbImage = docker.build("${params.ARM_IMAGE_PREFIX}-db-migration:$BRANCH", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile_db_migration.arm64v8 .")
                                docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) { armDbImage.push() }

                                sh "bash -c 'PYTHON2_IMAGE=${params.PYTHON2_ARM_IMAGE} envsubst \"\\\$PYTHON2_IMAGE\" < Dockerfile_config_init.tpl > Dockerfile_config_init.arm64v8'"
                                armConfigInitImage = docker.build("${params.ARM_IMAGE_PREFIX}-config-init:$BRANCH", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile_config_init.arm64v8 .")
                                docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) { armConfigInitImage.push()}

                                sh "bash -c 'ALPINE_IMAGE=${params.ALPINE_ARM_IMAGE} envsubst \"\\\$ALPINE_IMAGE\" < Dockerfile_config_readiness.tpl > Dockerfile_config_readiness.arm64v8'"
                                armConfigReadinessImage = docker.build("${params.ARM_IMAGE_PREFIX}-config-readiness:$BRANCH", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile_config_readiness.arm64v8 .")
                                docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) { armConfigReadinessImage.push()}
                            }
                        }
                    }
                )
            }
        }
    }
    post {
        failure {
            script {
                def ownerPhones = JsonOutput.toJson("${OWNER_PHONE}".split(","))
                def ownerAt = "${OWNER_PHONE}".split(",").collect { "@$it" }.join(' ')
                def commitMessage = sh (script: 'git log -1 --format="%B" ${GIT_COMMIT}', returnStdout: true).trim()
                def commitAuthor = sh (script: 'git log -1 --format="%ae" ${GIT_COMMIT}', returnStdout: true).trim()
                def payload = """{
                    "markdown": {
                        "title": "构建失败 - ${PROJECT_NAME}",
                        "text": "### 构建失败 - ${PROJECT_NAME}\n\n * 仓库：${REPO}\n * 分支：${BRANCH}\n * 详情：${env.BUILD_URL}console\n * 提交记录：${commitMessage}\n * 作者：${commitAuthor}\n\n${ownerAt}"
                    },
                    "msgtype": "markdown",
                    "at": {
                        "atMobiles": ${ownerPhones},
                        "isAtAll": false
                    }
                }"""
                httpRequest contentType: 'APPLICATION_JSON_UTF8', httpMode: 'POST', requestBody: payload, url: "$DING_URL"
            }
        }
    }
}
