
DROP TABLE IF EXISTS CnchMergeTree;

CREATE TABLE CnchMergeTree (x UInt64) ENGINE = CnchMergeTree ORDER BY x;
INSERT INTO CnchMergeTree VALUES (1);

SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM CnchMergeTree WHERE x IN (SELECT * FROM numbers(10000000))))))))))));

SET force_primary_key = 1;

SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM CnchMergeTree WHERE x IN (SELECT * FROM numbers(10000000))))))))))));

DROP TABLE CnchMergeTree;
