USE test;
DROP TABLE IF EXISTS a1;
DROP TABLE IF EXISTS a2;
SET send_logs_level = 'none';
CREATE TABLE a1(a UInt8, b UInt8) ENGINE=CnchMergeTree ORDER BY a;
CREATE TABLE a2(a UInt8, b UInt8) ENGINE=CnchMergeTree ORDER BY a;

INSERT INTO a1 VALUES (1, 1);
INSERT INTO a1 VALUES (1, 2);
INSERT INTO a1 VALUES (1, 3);
INSERT INTO a2 VALUES (1, 2);
INSERT INTO a2 VALUES (1, 3);
INSERT INTO a2 VALUES (1, 4);

SELECT a1.a, a1.b FROM a1 LEFT JOIN (SELECT a, b FROM a2) js2 ON a1.a = js2.a ORDER BY a1.b SETTINGS join_default_strictness='ANY';
SELECT a1.a, a1.b FROM a1 LEFT JOIN (SELECT a, b FROM a2) js2 ON a1.a = js2.a ORDER BY a1.b; -- default SETTINGS join_default_strictness='ALL';

DROP TABLE IF EXISTS a1;
DROP TABLE IF EXISTS a2;
