USE test;
drop table if exists test.tab;
create table test.tab (a String, b StringWithDictionary) engine = CnchMergeTree order by a;
insert into test.tab values ('a_1', 'b_1'), ('a_2', 'b_2');
select count() from test.tab;
select a from test.tab group by a order by a;
select b from test.tab group by b order by b;
select length(b) as l from test.tab group by length(b);
select sum(length(a)), b from test.tab group by b order by b;
select sum(length(b)), a from test.tab group by a order by a;
select a, b from test.tab group by a, b order by a, b;
select sum(length(a)) from test.tab group by b, b || '_';
select length(b) as l from test.tab group by length(b);
select length(b) as l from test.tab group by length(b), length(b) + 1;
select length(b) as l from test.tab group by length(b), length(b) + 1, length(b) + 2;
select length(b) as l from test.tab group by length(b), length(b) + 1, length(b) + 2, length(b) + 3;
select length(b) as l from test.tab group by length(b), length(b) + 1, length(b) + 2, length(b) + 3, length(b) + 4;
select length(b) as l from test.tab group by length(b), length(b) + 1, length(b) + 2, length(b) + 3, length(b) + 4, length(b) + 5;
select a, length(b) as l from test.tab group by a, length(b), length(b) + 1 order by a;
select b, length(b) as l from test.tab group by b, length(b), length(b) + 1 order by b;
select a, b, length(b) as l from test.tab group by a, b, length(b), length(b) + 1 order by a, b;
drop table if exists test.tab;

