
DROP TABLE IF EXISTS mt;
CREATE TABLE mt (x UInt8, s String) ENGINE = CnchMergeTree ORDER BY tuple();

INSERT INTO mt VALUES (1, 'Hello, world!');
SELECT * FROM mt;

ALTER TABLE mt ADD COLUMN y UInt8 DEFAULT 0;
INSERT INTO mt VALUES (2, 'Goodbye.', 3);
SELECT * FROM mt ORDER BY x;

SELECT s FROM mt PREWHERE x AND y ORDER BY s;
SELECT s, y FROM mt PREWHERE x AND y ORDER BY s;

DROP TABLE mt;
