DROP TABLE IF EXISTS cnch_partial_part;
CREATE TABLE cnch_partial_part(a String, b String) ENGINE = CnchMergeTree() ORDER BY a;
INSERT INTO cnch_partial_part values ('a', '1'), ('b', '2');
SET cnch_part_allocation_algorithm = 3;
SELECT a, b FROM cnch_partial_part;
ALTER TABLE cnch_partial_part MODIFY COLUMN b UInt8;
SYSTEM START MERGES cnch_partial_part;
SELECT sleep(3) FORMAT Null;
OPTIMIZE TABLE cnch_partial_part;
SELECT sleep(3) FORMAT Null;
SELECT a, b FROM cnch_partial_part;
DROP TABLE cnch_partial_part;
