DROP TABLE IF EXISTS window_frame_between;
CREATE TABLE window_frame_between
(
    a UInt64,
    b Float64
)
ENGINE = CnchMergeTree() ORDER BY tuple();

INSERT INTO window_frame_between (a, b)
VALUES (0, 0) (0, 1) (0, 2) (0, 3) (0, 4) (1, 6) (1, 7) (2, 8) (5, 9) (5, 10) (4, 11) (2, 12) (3, 13) (0, -5);

SELECT
  a,
  b,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) as res1,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN UNBOUNDED PRECEDING AND (3- 1) PRECEDING) as res2,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) as res3,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN UNBOUNDED PRECEDING AND (3-1) FOLLOWING) as res4,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as res5,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (2-1) PRECEDING AND CURRENT ROW) as res6,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (2-1) PRECEDING AND UNBOUNDED FOLLOWING) as res7,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (2-1) PRECEDING AND 3 FOLLOWING) as res8,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (2-1) PRECEDING AND (1+2) FOLLOWING) as res9,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (2-1) PRECEDING AND 0 PRECEDING) as res10,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (2-1) PRECEDING AND (2-2) PRECEDING) as res11,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN CURRENT ROW AND CURRENT ROW) as res12,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) as res13,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN CURRENT ROW AND 3 FOLLOWING) as res14,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN CURRENT ROW AND (1+2) FOLLOWING) as res15,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (1+1) FOLLOWING AND UNBOUNDED FOLLOWING) as res19,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (1+1) FOLLOWING AND 3 FOLLOWING) as res20,
  SUM(b) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN (1+1) FOLLOWING AND (1+2) FOLLOWING) as res21
FROM
  window_frame_between
ORDER BY a,b;
DROP TABLE window_frame_between;
