import HOTWORD_SETTING from "./HOTWORD_SETTING";
import HOTWORDS_HISTORY from "./HOTWORDS_HISTORY";
import HOTWORDS_TODAY from "./HOTWORDS_TODAY";
export default {
  HOTWORD_SETTING,
  HOTWORDS_TODAY,
  HOTWORDS_HISTORY
};
