select toYear(LO_ORDERDATE) AS d_year, S_NATION, P_CATEGORY, sum(LO_REVENUE - LO_SUPPLYCOST) as profit
from customer, supplier, part, lineorder
WHERE LO_CUSTKEY = C_CUSTKEY
AND LO_SUPPKEY = S_SUPPKEY
AND LO_PARTKEY = P_PARTKEY
and C_REGION = 'AMERICA'
and S_REGION = 'AMERICA'
and (toYear(LO_ORDERDATE) = 1997 or toYear(LO_ORDERDATE) = 1998)
and (P_MFGR = 'MFGR#1'
or P_MFGR = 'MFGR#2')
group by toYear(LO_ORDERDATE), S_NATION, P_CATEGORY Order by toYear(LO_ORDERDATE), S_NATION, P_CATEGORY;
