select toYear(LO_ORDERDATE) AS d_year, S_CITY, P_BRAND, sum(LO_REVENUE - LO_SUPPLYCOST) as profit
from customer, supplier, part, lineorder
WHERE LO_CUSTKEY = C_CUSTKEY
AND LO_SUPPKEY = S_SUPPKEY
AND LO_PARTKEY = P_PARTKEY
AND C_REGION = 'AMERICA'
AND S_NATION = 'UNITED STATES'
and (toYear(LO_ORDERDATE) = 1997 or toYear(LO_ORDERDATE) = 1998)
AND P_CATEGORY = 'MFGR#14'
group by toYear(LO_ORDERDATE), S_CITY, P_BRAND order by toYear(LO_ORDERDATE), S_CITY, P_BRAND;
