SELECT
    toYear(LO_ORDERDATE) AS year,
    S_NATION,
    P_CATEGORY,
    sum(LO_REVENUE - LO_SUPPLYCOST) AS profit
FROM lineorder_flat
WHERE C_REGION = 'AMERICA' AND S_REGION = 'AMERICA' AND (toYear(LO_ORDERDATE) = 1997 OR toYear(LO_ORDERDATE) = 1998) AND (P_MFGR = 'MFGR#1' OR P_MFGR = 'MFGR#2')
GROUP BY
    toYear(LO_ORDERDATE),
    S_NATION,
    P_CATEGORY
ORDER BY
    toYear(LO_ORDERDATE) ASC,
    S_NATION ASC,
    P_CATEGORY ASC;
