SELECT
    toYear(LO_ORDERDATE) AS year,
    S_CITY,
    P_BRAND,
    sum(LO_REVENUE - LO_SUPPLYCOST) AS profit
FROM lineorder_flat
WHERE S_NATION = 'UNITED STATES' AND (toYear(LO_ORDERDATE) = 1997 OR toYear(LO_ORDERDATE) = 1998) AND P_CATEGORY = 'MFGR#14'
GROUP BY
    toYear(LO_ORDERDATE),
    S_CITY,
    P_BRAND
ORDER BY
    toYear(LO_ORDERDATE) ASC,
    S_CITY ASC,
    P_BRAND ASC;
