FROM maven:3.8.3-adoptopenjdk-11 AS build
COPY . /app
WORKDIR /app
RUN mvn -Dmaven.test.skip=true clean package -U

# Release
FROM maven:3.8.3-adoptopenjdk-11 AS release
COPY ./sbin /app/sbin
RUN sh /app/sbin/ubuntu-install-debug.sh
USER root
WORKDIR /root
ARG APP_NAME=tesla-appmanager
# Copy Jars
COPY --from=build /app/${APP_NAME}-start-standalone/target/${APP_NAME}.jar /app/${APP_NAME}-standalone.jar
COPY --from=build /app/${APP_NAME}-start-standalone/target/${APP_NAME}/BOOT-INF/classes/application-docker.properties /app/config/application.properties
# Copy Resources
COPY --from=build /app/${APP_NAME}-start-standalone/target/${APP_NAME}/BOOT-INF/classes/dynamicscripts /app/dynamicscripts
COPY --from=build /app/${APP_NAME}-start-standalone/target/${APP_NAME}/BOOT-INF/classes/jinja /app/jinja
RUN wget -O /app/helm "https://abm-storage.oss-cn-zhangjiakou.aliyuncs.com/lib/helm" \
    && chmod +x /app/helm \
    && wget -O /app/kustomize "https://abm-storage.oss-cn-zhangjiakou.aliyuncs.com/lib/kustomize" \
    && chmod +x /app/kustomize \
    && wget -O /app/kubectl "https://abm-storage.oss-cn-zhangjiakou.aliyuncs.com/lib/kubectl" \
    && chmod +x /app/kubectl \
    && wget -O /app/terraform "https://abm-storage.oss-cn-zhangjiakou.aliyuncs.com/lib/terraform" \
    && chmod +x /app/terraform

WORKDIR /app
ENTRYPOINT ["/app/sbin/run_sreworks.sh"]