{
 "title": "Celeborn",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_WorkerCount_Value",
     "type": "timeseries",
     "description": "The count of active workers.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "metrics_WorkerCount_Value" }
     ]
    },
    {
     "title": "metrics_RegisteredShuffleCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "metrics_RegisteredShuffleCount_Value"
      }
     ]
    }
   ]
  },
  {
   "title": "Master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_IsActiveMaster_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "metrics_IsActiveMaster_Value" }
     ]
    },
    {
     "title": "metrics_PartitionSize_Value",
     "type": "timeseries",
     "description": "The size of estimated shuffle partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_PartitionSize_Value" }
     ]
    },
    {
     "title": "metrics_OfferSlotsTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OfferSlotsTime_Mean" }
     ]
    },
    {
     "title": "metrics_OfferSlotsTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OfferSlotsTime_Max" }
     ]
    },
    {
     "title": "metrics_ExcludedWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in excluded list. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "metrics_ExcludedWorkerCount_Value"
      }
     ]
    },
    {
     "title": "metrics_LostWorkers_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      { "expr": "metrics_LostWorkers_Value" }
     ]
    }
   ]
  },
  {
   "title": "Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_SlotsAllocated_Value",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "targets": [
      { "expr": "metrics_SlotsAllocated_Value" }
     ]
    },
    {
     "title": "metrics_ReserveSlotsTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_ReserveSlotsTime_Mean" }
     ]
    },
    {
     "title": "metrics_ReserveSlotsTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_ReserveSlotsTime_Max" }
     ]
    },
    {
     "title": "metrics_PausePushData_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      { "expr": "metrics_PausePushData_Value" }
     ]
    },
    {
     "title": "metrics_PausePushDataAndReplicate_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "metrics_PausePushDataAndReplicate_Value"
      }
     ]
    }
   ]
  },
  {
   "title": "PushRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PrimaryPushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataTime_Mean"
      }
     ]
    },
    {
     "title": "metrics_PrimaryPushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataTime_Max"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataTime_Mean"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataTime_Max"
      }
     ]
    },
    {
     "title": "metrics_WriteDataFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "metrics_WriteDataFailCount_Count"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataWriteFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataWriteFailCount_Count"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataFailCount_Count"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataTimeoutCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataTimeoutCount_Count"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataConnectionExceptionCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataConnectionExceptionCount_Count"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataCreateConnectionFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataCreateConnectionFailCount_Count"
      }
     ]
    }
   ]
  },
  {
   "title": "FetchRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_OpenStreamTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OpenStreamTime_Mean" }
     ]
    },
    {
     "title": "metrics_OpenStreamTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OpenStreamTime_Max" }
     ]
    },
    {
     "title": "metrics_FetchChunkTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FetchChunkTime_Mean" }
     ]
    },
    {
     "title": "metrics_FetchChunkTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FetchChunkTime_Max" }
     ]
    }
   ]
  },
  {
   "title": "FlushDataRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_TakeBufferTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_TakeBufferTime_Mean" }
     ]
    },
    {
     "title": "metrics_TakeBufferTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_TakeBufferTime_Max" }
     ]
    },
    {
     "title": "metrics_FlushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FlushDataTime_Mean" }
     ]
    },
    {
     "title": "metrics_FlushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FlushDataTime_Max" }
     ]
    },
    {
     "title": "metrics_CommitFilesTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_CommitFilesTime_Mean" }
     ]
    },
    {
     "title": "metrics_CommitFilesTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_CommitFilesTime_Max" }
     ]
    }
   ]
  },
  {
   "title": "MemoryRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_NettyMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_NettyMemory_Value" }
     ]
    },
    {
     "title": "metrics_DiskBuffer_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_DiskBuffer_Value" }
     ]
    },
    {
     "title": "metrics_push_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_push_usedHeapMemory_Value"
      }
     ]
    },
    {
     "title": "metrics_push_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_push_usedDirectMemory_Value"
      }
     ]
    },
    {
     "title": "metrics_fetch_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_fetch_usedHeapMemory_Value"
      }
     ]
    },
    {
     "title": "metrics_fetch_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_fetch_usedDirectMemory_Value"
      }
     ]
    },
    {
     "title": "metrics_replicate_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_replicate_usedHeapMemory_Value"
      }
     ]
    },
    {
     "title": "metrics_replicate_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_replicate_usedDirectMemory_Value"
      }
     ]
    },
    {
     "title": "ReadBufferAllocatedCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "metrics_ReadBufferAllocatedCount_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BufferStreamReadBuffer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_BufferStreamReadBuffer_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ReadBufferDispatcherRequestsLength",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "metrics_ReadBufferDispatcherRequestsLength_Value",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SortRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_SortTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_SortTime_Mean" }
     ]
    },
    {
     "title": "metrics_SortTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_SortTime_Max" }
     ]
    },
    {
     "title": "metrics_SortingFiles_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      { "expr": "metrics_SortingFiles_Value" }
     ]
    },
    {
     "title": "metrics_SortedFiles_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      { "expr": "metrics_SortedFiles_Value" }
     ]
    },
    {
     "title": "metrics_SortMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_SortMemory_Value" }
     ]
    },
    {
     "title": "metrics_SortedFileSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      { "expr": "metrics_SortedFileSize_Value" }
     ]
    }
   ]
  },
  {
   "title": "CongestionRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PotentialConsumeSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "metrics_PotentialConsumeSpeed_Value"
      }
     ]
    },
    {
     "title": "metrics_WorkerConsumeSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "metrics_WorkerConsumeSpeed_Value"
      }
     ]
    },
    {
     "title": "metrics_UserProduceSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      { "expr": "metrics_UserProduceSpeed_Value" }
     ]
    }
   ]
  },
  {
   "title": "MapPartitionRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PrimaryPushDataHandshakeTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataHandshakeTime_Mean"
      }
     ]
    },
    {
     "title": "metrics_PrimaryPushDataHandshakeTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataHandshakeTime_Max"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataHandshakeTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataHandshakeTime_Mean"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataHandshakeTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataHandshakeTime_Max"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionStartTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionStartTime_Mean"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionStartTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionStartTime_Max"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionStartTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionStartTime_Mean"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionStartTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionStartTime_Max"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionFinishTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionFinishTime_Mean"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionFinishTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionFinishTime_Max"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionFinishTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionFinishTime_Mean"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionFinishTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionFinishTime_Max"
      }
     ]
    },
    {
     "title": "metrics_PushDataHandshakeFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "metrics_PushDataHandshakeFailCount_Count"
      }
     ]
    },
    {
     "title": "metrics_RegionStartFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "targets": [
      {
       "expr": "metrics_RegionStartFailCount_Count"
      }
     ]
    },
    {
     "title": "metrics_RegionStartFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
     "targets": [
      {
       "expr": "metrics_RegionStartFailCount_Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Credit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CreditStreamCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "metrics_CreditStreamCount_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ActiveMapPartitionCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "metrics_ActiveMapPartitionCount_Value",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_JVMCPUTime_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "metrics_JVMCPUTime_Value", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "metrics_LastMinuteSystemLoad_Value",
     "type": "timeseries",
     "description": "The system load average for the last minute.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_LastMinuteSystemLoad_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "metrics_DeviceOSFreeBytes_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceOSFreeBytes_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "metrics_DeviceCelebornFreeBytes_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceCelebornFreeBytes_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "metrics_AvailableProcessors_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_AvailableProcessors_Value",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "UserConsumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_diskFileCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "targets": [
      { "expr": "metrics_diskFileCount_Value" }
     ]
    },
    {
     "title": "metrics_diskBytesWritten_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_diskBytesWritten_Value" }
     ]
    },
    {
     "title": "metrics_hdfsFileCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "targets": [
      { "expr": "metrics_hdfsFileCount_Value" }
     ]
    },
    {
     "title": "metrics_hdfsBytesWritten_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_hdfsBytesWritten_Value" }
     ]
    }
   ]
  }
 ]
}