{
 "title": "Celeborn",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "metrics_WorkerCount_Value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "metrics_WorkerCount_Value" }
   ]
  },
  {
   "title": "metrics_BlacklistedWorkerCount_Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "metrics_BlacklistedWorkerCount_Value"
    }
   ]
  },
  {
   "title": "metrics_RegisteredShuffleCount_Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "metrics_RegisteredShuffleCount_Value"
    }
   ]
  },
  {
   "title": "metrics_OfferSlotsTime_Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_OfferSlotsTime_Mean" }
   ]
  },
  {
   "title": "metrics_OfferSlotsTime_Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_OfferSlotsTime_Max" }
   ]
  },
  { "title": "worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "metrics_SlotsAllocated_Value",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "metrics_SlotsAllocated_Value" }
   ]
  },
  {
   "title": "metrics_MasterPushDataTime_Mean",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_MasterPushDataTime_Mean"
    }
   ]
  },
  {
   "title": "metrics_MasterPushDataTime_Max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_MasterPushDataTime_Max" }
   ]
  },
  {
   "title": "metrics_SlavePushDataTime_Mean",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_SlavePushDataTime_Mean" }
   ]
  },
  {
   "title": "metrics_SlavePushDataTime_Max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_SlavePushDataTime_Max" }
   ]
  },
  {
   "title": "metrics_ReserveSlotsTime_Mean",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_ReserveSlotsTime_Mean" }
   ]
  },
  {
   "title": "metrics_ReserveSlotsTime_Max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_ReserveSlotsTime_Max" }
   ]
  },
  {
   "title": "metrics_CommitFilesTime_Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_CommitFilesTime_Mean" }
   ]
  },
  {
   "title": "metrics_CommitFilesTime_Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "metrics_CommitFilesTime_Max" }
   ]
  },
  {
   "title": "metrics_PushDataFailCount_Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "metrics_PushDataFailCount_Count"
    }
   ]
  },
  {
   "title": "FetchRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_FetchChunkTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FetchChunkTime_Mean" }
     ]
    },
    {
     "title": "metrics_FetchChunkTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FetchChunkTime_Max" }
     ]
    },
    {
     "title": "metrics_OpenStreamTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OpenStreamTime_Mean" }
     ]
    },
    {
     "title": "metrics_OpenStreamTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OpenStreamTime_Max" }
     ]
    }
   ]
  },
  {
   "title": "FlushDataRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_ReserveSlotsTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_ReserveSlotsTime_Mean" }
     ]
    },
    {
     "title": "metrics_ReserveSlotsTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_ReserveSlotsTime_Max" }
     ]
    },
    {
     "title": "metrics_TakeBufferTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_TakeBufferTime_Mean" }
     ]
    },
    {
     "title": "metrics_TakeBufferTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_TakeBufferTime_Max" }
     ]
    },
    {
     "title": "metrics_FlushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FlushDataTime_Mean" }
     ]
    },
    {
     "title": "metrics_FlushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FlushDataTime_Max" }
     ]
    }
   ]
  },
  {
   "title": "MemoryRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_NettyMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "metrics_NettyMemory_Value" }
     ]
    },
    {
     "title": "metrics_DiskBuffer_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "metrics_DiskBuffer_Value" }
     ]
    },
    {
     "title": "metrics_PausePushData_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      { "expr": "metrics_PausePushData_Value" }
     ]
    },
    {
     "title": "metrics_PausePushDataAndReplicate_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "metrics_PausePushDataAndReplicate_Value"
      }
     ]
    }
   ]
  },
  {
   "title": "SortRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_SortTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_SortTime_Mean" }
     ]
    },
    {
     "title": "metrics_SortTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_SortTime_Max" }
     ]
    },
    {
     "title": "metrics_SortingFiles_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      { "expr": "metrics_SortingFiles_Value" }
     ]
    },
    {
     "title": "metrics_SortMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "metrics_SortMemory_Value" }
     ]
    }
   ]
  }
 ]
}