FROM sw-postrun:latest
COPY ./APP-META-PRIVATE/postrun /app/postrun
ENV SREWORKS_INIT "enable"
RUN pip install requests requests_oauthlib
RUN rm -rf /app/postrun/00_init_app_manager_flow.py && \
    apk update && \
    apk add wget bind-tools