FROM python:alpine

RUN wget https://sreworks.oss-cn-beijing.aliyuncs.com/bin/mc-linux-amd64 -O /root/mc && chmod +x /root/mc

ENV MINIO_ENDPOINT http://minio.c38cca9c474484bdc9873f44f733d8bcd.cn-beijing.alicontainer.com
ENV MINIO_ACCESS_KEY XmizyTRKhgYTrVkK
ENV MINIO_SECRET_KEY Df229gtwZ4bssMzK23VJXq9vrGqpxdHA

RUN mkdir /root/storage
RUN /root/mc alias set sw ${MINIO_ENDPOINT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} && /root/mc cp --recursive sw/public/v1.0/ /root/storage/


