def PROJECT_NAME = (env.JOB_NAME.tokenize('/') as String[])[0]
def BRANCH = env.BRANCH_NAME
def REPO = scm.getUserRemoteConfigs()[0].getUrl()
def TEST_RESULT

pipeline {
    options {
        disableConcurrentBuilds()
    }
    triggers {
        pollSCM('*/2 * * * *')
    }
    agent any
     parameters {
        string(name: 'MIGRATE_URL', defaultValue: 'http://abm-storage.oss-accelerate.aliyuncs.com/lib/migrate/4.11.0/migrate.linux-arm64.tar.gz', description: '')
     }
    stages {
        stage("Clone Repo") {
            steps {
                git credentialsId: "$GIT_CREDENTIAL",
                    url: REPO,
                    branch: BRANCH
            }
        }
        stage("Build & Push Documentation Images") {
            agent any
            when {
                branch 'master'
            }
            steps {
                script {
                    x86ApplicationImage = docker.build("reg.docker.alibaba-inc.com/abm-aone/migrate", "--pull --no-cache -f ./Dockerfile .")
                    docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) {
                        x86ApplicationImage.push()
                    }
                    armApplicationImage = docker.build("reg.docker.alibaba-inc.com/abm-arm64v8/migrate", "--build-arg MIGRATE_URL=${params.MIGRATE_URL} --pull --no-cache -f ./Dockerfile.arm64v8 .")
                    docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) {
                        armApplicationImage.push()
                    }
                }
            }
        }
    }
}