FROM python:3.9-slim

WORKDIR /worker

COPY examples/opcuaDeviceShifu/server/requirements.txt requirements.txt
COPY examples/opcuaDeviceShifu/server/server.py server.py
COPY pkg/logger pkg/logger

RUN pip3 install -r requirements.txt

CMD [ "python3","/worker/server.py" ]