-- -- ----------------------------
-- -- ENTITY META INIT
-- -- ----------------------------
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (1, 'TEAM', '团队', '<ods_team_{now/M{yyyy.MM}}>', 'ods_team', 1, 'ods', 'M', 90, '团队实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (2, 'TEAM_USER', '团队成员', '<ods_team_user_{now/M{yyyy.MM}}>', 'ods_team_user', 1, 'ods', 'M', 90, '团队成员实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (3, 'TEAM_ACCOUNT', '团队云账户', '<ods_team_account_{now/M{yyyy.MM}}>', 'ods_team_account', 1, 'ods', 'M', 90, '团队云账户实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (4, 'TEAM_REPO', '团队托管仓库', '<ods_team_repo_{now/M{yyyy.MM}}>', 'ods_team_repo', 1, 'ods', 'M', 90, '团队托管仓库实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (5, 'TEAM_REGISTRY', '团队注册信息', '<ods_team_registry_{now/M{yyyy.MM}}>', 'ods_team_registry', 1, 'ods', 'M', 90, '团队注册信息实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (6, 'CLUSTER', '集群', '<ods_cluster_{now/M{yyyy.MM}}>', 'ods_cluster', 1, 'ods', 'M', 90, '集群实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (7, 'APP', '应用', '<ods_app_{now/M{yyyy.MM}}>', 'ods_app', 1, 'ods', 'M', 90, '应用实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (8, 'APP_COMPONENT', '应用组件', '<ods_app_component_{now/M{yyyy.MM}}>', 'ods_app_component', 1, 'ods', 'M', 90, '应用组件实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (9, 'METRIC', '指标定义', '<ods_metric_{now/M{yyyy.MM}}>', 'ods_metric', 1, 'ods', 'M', 90, '指标定义实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (10, 'EVENT', '事件定义', '<ods_event_{now/M{yyyy.MM}}>', 'ods_event', 1, 'ods', 'M', 90, '事件定义实体');
-- INSERT INTO `sw_entity` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `partition_format`, `lifecycle`, `description`) VALUES (11, 'EVENT_INSTANCE', '事件实例', '<ods_event_instance_{now/M{yyyy.MM}}>', 'ods_event_instance', 1, 'ods', 'M', 90, '事件实例实体');
--
-- -- ----------------------------
-- -- ENTITY COLUMN INIT
-- -- ----------------------------
-- -- TEAM ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (1, 1, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (2, 1, 'id', '团队ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (3, 1, 'name', '团队名称', 'name', 'STRING', 1, 0, '团队名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (4, 1, 'avatar', '团队头像', 'avatar', 'STRING', 1, 1, '团队头像链接');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (5, 1, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '团队创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (6, 1, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '团队最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (7, 1, 'creator', '创建人', 'creator', 'STRING', 1, 1, '团队创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (8, 1, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '团队最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (9, 1, 'visible_scope', '可见范围', 'visible_scope', 'STRING', 1, 1, '团队可见属性');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (10, 1, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- TEAM_USER ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (11, 2, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (12, 2, 'id', '用户ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (13, 2, 'user', '用户名称', 'user', 'STRING', 1, 0, '用户名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (14, 2, 'role', '角色', 'role', 'STRING', 1, 0, '用户角色(权限)');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (15, 2, 'team_id', '归属团队ID', 'team_id', 'STRING', 1, 0, '用户所属的团队ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (16, 2, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '用户创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (17, 2, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '用户信息的最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (18, 2, 'creator', '创建人', 'creator', 'STRING', 1, 1, '用户创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (19, 2, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '用户信息的最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (20, 2, 'gmt_access', '访问时间', 'gmt_access', 'DATE', 1, 1, '用户访问时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (21, 2, 'is_concern', '是否关注', 'is_concern', 'INTEGER', 1, 1, '待补充说明');
--
-- -- TEAM_ACCOUNT ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (22, 3, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (23, 3, 'id', '账户ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (24, 3, 'name', '账户名称', 'name', 'STRING', 1, 0, '账户名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (25, 3, 'type', '账户类型', 'type', 'STRING', 1, 0, '账户类型');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (26, 3, 'team_id', '归属团队ID', 'team_id', 'STRING', 1, 0, '账户所属的团队ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (27, 3, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '账户创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (28, 3, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '账户最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (29, 3, 'creator', '创建人', 'creator', 'STRING', 1, 1, '账户创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (30, 3, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '账户最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (31, 3, 'detail', '账户详情', 'detail', 'STRING', 1, 1, '账户详情信息');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (32, 3, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- TEAM_REPO ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (33, 4, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (34, 4, 'id', '仓库ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (35, 4, 'name', '仓库名称', 'name', 'STRING', 1, 0, '仓库名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (36, 4, 'url', '仓库链接', 'url', 'STRING', 1, 0, '仓库链接');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (37, 4, 'team_id', '归属团队ID', 'team_id', 'STRING', 1, 0, '仓库所属的团队ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (38, 4, 'ci_account', '仓库账户', 'ci_account', 'STRING', 1, 1, '仓库账户');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (39, 4, 'ci_token', '仓库令牌', 'ci_token', 'STRING', 1, 1, '仓库令牌');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (40, 4, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '账户创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (41, 4, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '账户最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (42, 4, 'creator', '创建人', 'creator', 'STRING', 1, 1, '账户创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (43, 4, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '账户最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (44, 4, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- TEAM_REGISTRY ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (45, 5, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (46, 5, 'id', '注册ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (47, 5, 'name', '注册名称', 'name', 'STRING', 1, 0, '注册名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (48, 5, 'url', '注册链接', 'url', 'STRING', 1, 0, '注册链接');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (49, 5, 'team_id', '归属团队ID', 'team_id', 'STRING', 1, 0, '所属的团队ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (50, 5, 'auth', '认证信息', 'auth', 'STRING', 1, 1, '认证信息');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (51, 5, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (52, 5, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (53, 5, 'creator', '创建人', 'creator', 'STRING', 1, 1, '创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (54, 5, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (55, 5, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- CLUSTER ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (56, 6, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (57, 6, 'id', '集群ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (58, 6, 'name', '集群名称', 'name', 'STRING', 1, 0, '集群名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (59, 6, 'cluster_name', '集群code', 'cluster_name', 'STRING', 1, 0, '集群code');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (60, 6, 'team_id', '归属团队ID', 'team_id', 'STRING', 1, 0, '集群所属的团队ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (61, 6, 'account_id', '关联账户', 'account_id', 'STRING', 1, 0, '集群关联账户');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (62, 6, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '集群创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (63, 6, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '集群最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (64, 6, 'creator', '创建人', 'creator', 'STRING', 1, 1, '集群创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (65, 6, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '集群最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (66, 6, 'kubeconfig', 'kube配置', 'kubeconfig', 'STRING', 1, 1, '集群kube配置');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (67, 6, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- APP ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (68, 7, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (69, 7, 'id', '应用ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (70, 7, 'name', '应用名称', 'name', 'STRING', 1, 0, '应用名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (71, 7, 'team_id', '归属团队ID', 'team_id', 'STRING', 1, 0, '应用所属的团队ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (72, 7, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '应用创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (73, 7, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '应用最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (74, 7, 'creator', '创建人', 'creator', 'STRING', 1, 1, '集群创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (75, 7, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '应用最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (76, 7, 'annotations', '应用注解', 'annotations', 'STRING', 1, 1, '应用注解');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (77, 7, 'labels', '应用标签', 'labels', 'STRING', 1, 1, '应用标签');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (78, 7, 'detail', '应用详情', 'detail', 'STRING', 1, 1, '应用详情');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (79, 7, 'display', '显示', 'display', 'INTEGER', 1, 1, '显示');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (80, 7, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- APP_COMPONENT ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (81, 8, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (82, 8, 'id', '组件ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (83, 8, 'name', '组件名称', 'name', 'STRING', 1, 0, '组件名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (84, 8, 'app_id', '归属应用ID', 'app_id', 'STRING', 1, 0, '组件所属的应用ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (85, 8, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '组件创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (86, 8, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '组件最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (87, 8, 'creator', '创建人', 'creator', 'STRING', 1, 1, '组件创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (88, 8, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '组件最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (89, 8, 'type', '组件类型', 'type', 'STRING', 1, 0, '组件类型');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (90, 8, 'type_detail', '组件类型详情', 'type_detail', 'STRING', 1, 1, '组件类型详情');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (91, 8, 'ex_id', '扩展ID', 'ex_id', 'LONG', 1, 1, '扩展ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (92, 8, 'detail', '组件详情', 'detail', 'STRING', 1, 1, '组件详情');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (93, 8, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- METRIC ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (94, 9, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (95, 9, 'id', '指标ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (96, 9, 'name', '指标名称', 'name', 'STRING', 1, 0, '指标名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (97, 9, 'type', '指标类型', 'type', 'STRING', 1, 0, '指标类型');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (98, 9, 'app_id', '归属应用ID', 'app_id', 'STRING', 1, 0, '指标所属的应用ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (99, 9, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '指标归属实体');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (100, 9, 'table', '存储表名', 'table', 'STRING', 1, 0, '存储索引(ES)');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (101, 9, 'index_path', '指标值索引', 'index_path', 'STRING', 1, 0, '指标值索引路径(ES)');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (102, 9, 'tags', '指标标签', 'tags', 'STRING', 1, 1, '指标标签');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (103, 9, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '指标创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (104, 9, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '指标最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (105, 9, 'creator', '创建人', 'creator', 'STRING', 1, 1, '指标创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (106, 9, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '指标最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (107, 9, 'build_in', '内置指标', 'build_in', 'BOOLEAN', 1, 1, '内置指标');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (108, 9, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- EVENT ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (109, 10, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (110, 10, 'id', '事件ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (111, 10, 'name', '事件名称', 'name', 'STRING', 1, 0, '事件名称');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (112, 10, 'category', '类型标识', 'category', 'STRING', 1, 0, '类型标识');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (113, 10, 'app_id', '归属应用ID', 'app_id', 'STRING', 1, 0, '事件所属的应用ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (114, 10, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '事件归属实体');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (115, 10, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '事件创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (116, 10, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '事件最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (117, 10, 'creator', '创建人', 'creator', 'STRING', 1, 1, '事件创建人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (118, 10, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '事件最近修改人');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (119, 10, 'ex_config', '扩展配置', 'ex_config', 'OBJECT', 1, 1, '扩展配置');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (120, 10, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- EVENT_INSTANCE ENTITY
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (121, 11, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (122, 11, 'id', '事件实例ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (123, 11, 'def_id', '关联定义ID', 'def_id', 'STRING', 1, 0, '事件实例所属的定义ID');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (124, 11, 'entity_value', '实体值', 'entity_value', 'STRING', 1, 0, '实体值');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (125, 11, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '事件实例创建时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (126, 11, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '事件实例最近修改时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (127, 11, 'gmt_occur', '发生时间', 'gmt_occur', 'DATE', 1, 1, '事件实例发生时间');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (128, 11, 'source', '事件来源', 'source', 'STRING', 1, 1, '事件来源');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (129, 11, 'content', '详情', 'content', 'STRING', 1, 1, '详情');
-- INSERT INTO `sw_entity_field` (`id`, `entity_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (130, 11, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');