-- -- ----------------------------
-- -- MODEL META INIT
-- -- ----------------------------
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (1, 'RISK', '风险定义', '<dwd_stability_risk_{now/M{yyyy.MM}}>', 'dwd_stability_risk', 1, 'dwd', 1, 'M', 90, '风险定义模型');
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (2, 'RISK_INSTANCE', '风险实例', '<dwd_stability_risk_instance_{now/M{yyyy.MM}}>', 'dwd_stability_risk_instance', 1, 'dwd', 1, 'M', 90, '风险实例模型');
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (3, 'ALERT', '告警定义', '<dwd_stability_alert_{now/M{yyyy.MM}}>', 'dwd_stability_alert', 1, 'dwd', 1, 'M', 90, '告警定义模型');
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (4, 'ALERT_INSTANCE', '告警实例', '<dwd_stability_alert_instance_{now/M{yyyy.MM}}>', 'dwd_stability_alert_instance', 1, 'dwd', 1, 'M', 90, '告警实例模型');
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (5, 'INCIDENT', '异常定义', '<dwd_stability_incident_{now/M{yyyy.MM}}>', 'dwd_stability_incident', 1, 'dwd', 1, 'M', 90, '异常定义模型');
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (6, 'INCIDENT_INSTANCE', '异常实例', '<dwd_stability_incident_instance_{now/M{yyyy.MM}}>', 'dwd_stability_incident_instance', 1, 'dwd', 1, 'M', 90, '异常实例模型');
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (7, 'FAILURE', '故障定义', '<dwd_stability_failure_{now/M{yyyy.MM}}>', 'dwd_stability_failure', 1, 'dwd', 1, 'M', 90, '故障定义模型');
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (8, 'FAILURE_INSTANCE', '故障实例', '<dwd_stability_failure_instance_{now/M{yyyy.MM}}>', 'dwd_stability_failure_instance', 1, 'dwd', 1, 'M', 90, '故障实例模型');
-- INSERT INTO `sw_model` (`id`, `name`, `alias`, `table_name`, `table_alias`, `build_in`, `layer`, `domain_id`, `partition_format`, `lifecycle`, `description`) VALUES (9, 'INCIDENT_TYPE', '异常类型', '<dim_stability_incident_type_{now/M{yyyy.MM}}>', 'dim_stability_incident_type', 1, 'dim', 1, 'M', 90, '异常类型维度模型');
--
-- -- ----------------------------
-- -- MODEL COLUMN INIT
-- -- ----------------------------
-- -- RISK MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (1, 1, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (2, 1, 'id', '风险ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (3, 1, 'name', '风险名称', 'name', 'STRING', 1, 0, '风险名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (4, 1, 'category', '类型', 'category', 'STRING', 1, 0, '类型(risk)');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (5, 1, 'app_id', '归属应用ID', 'app_id', 'STRING', 1, 0, '风险所属的应用ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (6, 1, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '风险归属实体');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (7, 1, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (8, 1, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (9, 1, 'creator', '创建人', 'creator', 'STRING', 1, 1, '创建人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (10, 1, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '最近修改人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (11, 1, 'tags', '标签', 'tags', 'ARRAY', 1, 1, '风险标签');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (12, 1, 'storage_days', '实例保留天数', 'storage_days', 'INTEGER', 1, 1, '风险实例保留天数');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (13, 1, 'enable', '是否启用', 'enable', 'BOOLEAN', 1, 1, '是否启用');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (14, 1, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- RISK_INSTANCE MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (15, 2, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (16, 2, 'id', '风险实例ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (17, 2, 'def_id', '关联定义ID', 'def_id', 'STRING', 1, 0, '风险实例所属的定义ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (18, 2, 'def_name', '关联定义名称', 'def_name', 'STRING', 1, 0, '风险实例所属的定义名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (19, 2, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '风险归属实体');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (20, 2, 'entity_value', '实体值', 'entity_value', 'STRING', 1, 0, '实体值');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (21, 2, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '风险实例创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (22, 2, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '风险实例最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (23, 2, 'gmt_occur', '发生时间', 'gmt_occur', 'DATE', 1, 1, '风险发生时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (24, 2, 'source', '风险来源', 'source', 'STRING', 1, 1, '风险来源');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (25, 2, 'content', '风险详情', 'content', 'STRING', 1, 1, '风险详情');
--
-- -- ALERT MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (26, 3, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (27, 3, 'id', '告警ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (28, 3, 'name', '告警名称', 'name', 'STRING', 1, 0, '告警名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (29, 3, 'category', '类型', 'category', 'STRING', 1, 0, '类型(alert)');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (30, 3, 'app_id', '归属应用ID', 'app_id', 'STRING', 1, 0, '告警所属的应用ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (31, 3, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '告警归属实体');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (32, 3, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (33, 3, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (34, 3, 'creator', '创建人', 'creator', 'STRING', 1, 1, '创建人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (35, 3, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '最近修改人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (36, 3, 'storage_days', '实例保留天数', 'storage_days', 'INTEGER', 1, 1, '告警实例保留天数');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (37, 3, 'enable', '是否启用', 'enable', 'BOOLEAN', 1, 1, '是否启用');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (38, 3, 'alert_rule_configs', '告警规则', 'alert_rule_configs', 'ARRAY', 1, 1, '告警规则配置');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (39, 3, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- ALERT_INSTANCE MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (40, 4, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (41, 4, 'id', '告警实例ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (42, 4, 'def_id', '关联定义ID', 'def_id', 'STRING', 1, 0, '告警实例所属的定义ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (43, 4, 'def_name', '关联定义名称', 'def_name', 'STRING', 1, 0, '告警实例所属的定义名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (44, 4, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '告警归属实体');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (45, 4, 'entity_value', '实体值', 'entity_value', 'STRING', 1, 0, '实体值');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (46, 4, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '告警实例创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (47, 4, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '告警实例最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (48, 4, 'gmt_occur', '发生时间', 'gmt_occur', 'DATE', 1, 1, '告警发生时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (49, 4, 'source', '告警来源', 'source', 'STRING', 1, 1, '告警来源');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (50, 4, 'level', '告警等级', 'level', 'STRING', 1, 1, '告警等级');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (51, 4, 'receivers', '告警接收人', 'receivers', 'STRING', 1, 1, '告警接收人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (52, 4, 'content', '告警内容', 'content', 'STRING', 1, 1, '告警内容');
--
-- -- INCIDENT MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (53, 5, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (54, 5, 'id', '异常ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (55, 5, 'name', '异常名称', 'name', 'STRING', 1, 0, '异常名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (56, 5, 'category', '类型', 'category', 'STRING', 1, 0, '类型(incident)');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (57, 5, 'app_id', '归属应用ID', 'app_id', 'STRING', 1, 0, '异常所属的应用ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (58, 5, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '异常归属实体');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (59, 5, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (60, 5, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (61, 5, 'creator', '创建人', 'creator', 'STRING', 1, 1, '创建人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (62, 5, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '最近修改人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (63, 5, 'type_id', '异常类型ID', 'type_id', 'INTEGER', 1, 0, '异常类型ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (64, 5, 'type_label', '异常类型标识', 'type_label', 'STRING', 1, 0, '异常类型标识');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (65, 5, 'type_name', '异常类型名称', 'type_name', 'STRING', 1, 0, '异常类型名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (66, 5, 'self_healing', '是否自愈', 'self_healing', 'BOOLEAN', 1, 1, '是否自愈');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (67, 5, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- INCIDENT_INSTANCE MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (68, 6, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (69, 6, 'id', '异常实例ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (70, 6, 'def_id', '关联定义ID', 'def_id', 'STRING', 1, 0, '异常实例所属的定义ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (71, 6, 'def_name', '关联定义名称', 'def_name', 'STRING', 1, 0, '异常实例所属的定义名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (72, 6, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '异常归属实体');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (73, 6, 'entity_value', '实体值', 'entity_value', 'STRING', 1, 0, '实体值');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (74, 6, 'trace_id', '任务链ID', 'trace_id', 'STRING', 1, 0, '任务链ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (75, 6, 'span_id', '层次ID', 'span_id', 'STRING', 1, 0, '层次ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (76, 6, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '异常实例创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (77, 6, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '异常实例最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (78, 6, 'gmt_occur', '发生时间', 'gmt_occur', 'DATE', 1, 1, '异常发生时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (79, 6, 'gmt_recovery', '恢复时间', 'gmt_recovery', 'DATE', 1, 1, '异常恢复时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (80, 6, 'gmt_self_healing_start', '自愈开始时间', 'gmt_self_healing_start', 'DATE', 1, 1, '自愈开始时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (81, 6, 'gmt_self_healing_end', '自愈结束时间', 'gmt_self_healing_end', 'DATE', 1, 1, '自愈结束时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (82, 6, 'self_healing_status', '自愈状态', 'self_healing_status', 'STRING', 1, 1, '自愈状态');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (83, 6, 'source', '异常来源', 'source', 'STRING', 1, 1, '异常来源');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (84, 6, 'cause', '异常产生原因', 'cause', 'STRING', 1, 1, '异常产生原因');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (85, 6, 'options', '扩展信息', 'options', 'STRING', 1, 1, '用户自定义参数');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (86, 6, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- FAILURE MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (87, 7, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (88, 7, 'id', '故障ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (89, 7, 'name', '故障名称', 'name', 'STRING', 1, 0, '故障名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (90, 7, 'category', '类型', 'category', 'STRING', 1, 0, '类型(failure)');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (91, 7, 'app_id', '归属应用ID', 'app_id', 'STRING', 1, 0, '故障所属的应用ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (92, 7, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '故障归属实体');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (93, 7, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (94, 7, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (95, 7, 'creator', '创建人', 'creator', 'STRING', 1, 1, '创建人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (96, 7, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '最近修改人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (97, 7, 'ref_incident_def_id', '关联异常ID', 'ref_incident_def_id', 'STRING', 1, 0, '关联异常ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (98, 7, 'ref_incident_def_name', '关联异常名称', 'ref_incident_def_name', 'STRING', 1, 0, '关联异常名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (99, 7, 'ref_incident_type_id', '关联异常类型ID', 'ref_incident_type_id', 'INTEGER', 1, 0, '关联异常类型ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (100, 7, 'ref_incident_type_label', '关联异常类型标识', 'ref_incident_type_label', 'STRING', 1, 0, '关联异常类型标识');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (101, 7, 'ref_incident_type_name', '关联异常类型名称', 'ref_incident_type_name', 'STRING', 1, 0, '关联异常类型名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (102, 7, 'failure_level_rule', '故障等级定义规则', 'failure_level_rule', 'OBJECT', 1, 0, '故障等级定义规则');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (103, 7, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
--
-- -- FAILURE_INSTANCE MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (104, 8, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (105, 8, 'id', '故障实例ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (106, 8, 'name', '故障名称', 'name', 'STRING', 1, 0, '故障名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (107, 8, 'def_id', '关联定义ID', 'def_id', 'STRING', 1, 0, '故障实例所属的定义ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (108, 8, 'def_name', '关联定义名称', 'def_name', 'STRING', 1, 0, '故障实例所属的定义名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (109, 8, 'entity', '归属实体', 'entity', 'STRING', 1, 0, '故障归属实体');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (110, 8, 'entity_value', '实体值', 'entity_value', 'STRING', 1, 0, '实体值');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (111, 8, 'ref_incident_def_id', '关联异常ID', 'ref_incident_def_id', 'STRING', 1, 0, '关联异常ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (112, 8, 'ref_incident_def_name', '关联异常名称', 'ref_incident_def_name', 'STRING', 1, 0, '关联异常名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (113, 8, 'ref_incident_type_id', '关联异常类型ID', 'ref_incident_type_id', 'INTEGER', 1, 0, '关联异常类型ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (114, 8, 'ref_incident_type_label', '关联异常类型标识', 'ref_incident_type_label', 'STRING', 1, 0, '关联异常类型标识');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (115, 8, 'ref_incident_type_name', '关联异常类型名称', 'ref_incident_type_name', 'STRING', 1, 0, '关联异常类型名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (116, 8, 'incident_id', '异常实例ID', 'incident_id', 'STRING', 1, 0, '异常实例ID');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (117, 8, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '故障实例创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (118, 8, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '故障实例最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (119, 8, 'gmt_occur', '发生时间', 'gmt_occur', 'DATE', 1, 1, '故障发生时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (120, 8, 'level', '故障等级', 'level', 'STRING', 1, 0, '故障等级');
--
--
-- -- INCIDENT_TYPE MODEL
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (121, 9, 'ds', '分区列', 'ds', 'STRING', 1, 0, '时间分区字段');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (122, 9, 'id', '异常类型ID', 'id', 'STRING', 1, 0, '主键');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (123, 9, 'label', '异常类型标识', 'label', 'STRING', 1, 0, '唯一标识');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (124, 9, 'name', '异常类型名称', 'name', 'STRING', 1, 0, '异常类型名称');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (125, 9, 'mq_topic', '消息队列topic', 'mq_topic', 'STRING', 1, 0, '消息队列topic');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (126, 9, 'gmt_create', '创建时间', 'gmt_create', 'DATE', 1, 1, '创建时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (127, 9, 'gmt_modified', '修改时间', 'gmt_modified', 'DATE', 1, 1, '最近修改时间');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (128, 9, 'creator', '创建人', 'creator', 'STRING', 1, 1, '创建人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (129, 9, 'last_modifier', '最近修改人', 'last_modifier', 'STRING', 1, 1, '最近修改人');
-- INSERT INTO `sw_model_field` (`id`, `model_id`, `field`, `alias`, `dim`, `type`, `build_in`, `nullable`, `description`) VALUES (130, 9, 'description', '说明', 'description', 'STRING', 1, 1, '备注说明信息');
