# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM atlas-base:latest

ARG ATLAS_VERSION
ARG KAFKA_VERSION


COPY ./downloads/kafka_2.12-${KAFKA_VERSION}.tgz         /home/atlas/dist/

COPY ./scripts/atlas-kafka-setup.sh                     /home/atlas/scripts/
COPY ./scripts/atlas-kafka.sh                           /home/atlas/scripts/

RUN tar xvfz /home/atlas/dist/kafka_2.12-${KAFKA_VERSION}.tgz --directory=/opt/ && \
    ln -s /opt/kafka_2.12-${KAFKA_VERSION} /opt/kafka && \
    rm -f /home/atlas/dist/kafka_2.12-${KAFKA_VERSION}.tgz

ENV KAFKA_HOME /opt/kafka
ENV PATH       /usr/java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/kafka/bin

EXPOSE 9092

ENTRYPOINT [ "/home/atlas/scripts/atlas-kafka.sh" ]
