/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReservations implements ReservationInterface
type FakeReservations struct {
	Fake *FakeSchedulingV1alpha1
}

var reservationsResource = schema.GroupVersionResource{Group: "scheduling.koordinator.sh", Version: "v1alpha1", Resource: "reservations"}

var reservationsKind = schema.GroupVersionKind{Group: "scheduling.koordinator.sh", Version: "v1alpha1", Kind: "Reservation"}

// Get takes name of the reservation, and returns the corresponding reservation object, and an error if there is any.
func (c *FakeReservations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Reservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(reservationsResource, name), &v1alpha1.Reservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Reservation), err
}

// List takes label and field selectors, and returns the list of Reservations that match those selectors.
func (c *FakeReservations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReservationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(reservationsResource, reservationsKind, opts), &v1alpha1.ReservationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ReservationList{ListMeta: obj.(*v1alpha1.ReservationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ReservationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested reservations.
func (c *FakeReservations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(reservationsResource, opts))
}

// Create takes the representation of a reservation and creates it.  Returns the server's representation of the reservation, and an error, if there is any.
func (c *FakeReservations) Create(ctx context.Context, reservation *v1alpha1.Reservation, opts v1.CreateOptions) (result *v1alpha1.Reservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(reservationsResource, reservation), &v1alpha1.Reservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Reservation), err
}

// Update takes the representation of a reservation and updates it. Returns the server's representation of the reservation, and an error, if there is any.
func (c *FakeReservations) Update(ctx context.Context, reservation *v1alpha1.Reservation, opts v1.UpdateOptions) (result *v1alpha1.Reservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(reservationsResource, reservation), &v1alpha1.Reservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Reservation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeReservations) UpdateStatus(ctx context.Context, reservation *v1alpha1.Reservation, opts v1.UpdateOptions) (*v1alpha1.Reservation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(reservationsResource, "status", reservation), &v1alpha1.Reservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Reservation), err
}

// Delete takes name of the reservation and deletes it. Returns an error if one occurs.
func (c *FakeReservations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(reservationsResource, name), &v1alpha1.Reservation{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReservations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(reservationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ReservationList{})
	return err
}

// Patch applies the patch and returns the patched reservation.
func (c *FakeReservations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Reservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(reservationsResource, name, pt, data, subresources...), &v1alpha1.Reservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Reservation), err
}
