{
 "title": "node",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_boot_time{job=\"node-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "机器pod cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\",container_name!=\"POD\",instance=~\"$node.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "机器pod 内存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{job=\"kubelet\", image!=\"\",container_name!=\"POD\",instance=~\"$node.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{job=\"node-exporter\", mode=\"idle\", instance=~\"$node.*\"}[5m])) * 100)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=~\"$node.*\"} * 100",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=~\"$node.*\"} * 100",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", instance=~\"$node.*\"} * 100",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_Cached{job=\"node-exporter\", instance=~\"$node.*\"}\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=~\"$node.*\"}\n- node_memory_Cached{job=\"node-exporter\", instance=~\"$node.*\"}\n) * 100\n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=~\"$node.*\"}\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{job=\"node-exporter\", instance=~\"$node.*\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{job=\"node-exporter\", instance=~\"$node.*\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{job=\"node-exporter\",  instance=~\"$node.*\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$node.*\"})\n- sum(node_filesystem_avail{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$node.*\"})\n) * 100\n  /\nsum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$node.*\"})\n"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{job=\"node-exporter\", instance=~\"$node.*\", device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{job=\"node-exporter\", instance=~\"$node.*\", device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}