#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ -z $JAVA_HOME ]
then
  JAVA=`which java`
else
  JAVA=$JAVA_HOME/bin/java
fi

if [ -e $JAVA ]; then
  echo ""
else
  echo "Java not found."
  exit 1
fi

$JAVA -version 2>&1 | grep "version" | egrep -e "1.8" > /dev/null
if [ $? -ne 0 ]; then
  echo "Java 1.8 is required to run Apache Drill."
  exit 1
fi


CP=$DRILL_HOME/jars/*:$CP
CP=$DRILL_HOME/lib/*:$CP

CP=$CP:$DRILL_CONF_DIR

exec $JAVA $DRILL_JAVA_OPTS -cp $CP org.apache.drill.exec.server.Drillbit
