# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: tis build

on: workflow_dispatch
#   push:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
        #       - name: Check Style
        #         run: |
        #           ./mvnw -T 2C -B --no-snapshot-updates clean checkstyle:check
      #https://stackoverflow.com/questions/57711558/deploy-to-github-package-registry-from-github-action
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github_ibator</id><username>baisui1981</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          cat ~/.m2/settings.xml
          mvn -B package -Dmaven.test.skip=true -Pgithub-repo,aliyun-repo  --file pom.xml -s ~/.m2/settings.xml
