CREATE TABLE `instancedetail` (
  `instance_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `order_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `batch_msg` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '批次信息：时:分 点菜人',
  `type` smallint(3) NOT NULL DEFAULT '0' COMMENT '商品类型(0:菜 1: 打包盒)',
  `ext` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '扩展字段，不适合做查询字段',
  `waitinginstance_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `kind` smallint(6) NOT NULL DEFAULT '1' COMMENT '1:普通菜;2:套菜;3:自定义菜;4:自定义套菜',
  `parent_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `pricemode` smallint(6) NOT NULL DEFAULT '1' COMMENT '1:固定价;2:浮动价',
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `makename` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `taste` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `spec_detail_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `num` decimal(10,2) NOT NULL DEFAULT '0.00',
  `account_num` decimal(12,4) NOT NULL DEFAULT '0.0000',
  `unit` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `account_unit` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `member_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `fee` decimal(18,2) NOT NULL DEFAULT '0.00',
  `ratio` decimal(10,2) NOT NULL DEFAULT '0.00',
  `ratio_fee` decimal(18,2) NOT NULL DEFAULT '0.00',
  `ratio_cause` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `status` smallint(6) NOT NULL DEFAULT '1' COMMENT '状态：1/未确认 2/正常 3/退菜标志',
  `kindmenu_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `kindmenu_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `menu_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `memo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_ratio` smallint(6) DEFAULT '0',
  `entity_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_valid` smallint(6) NOT NULL DEFAULT '1',
  `create_time` bigint(20) DEFAULT '0',
  `op_time` bigint(20) DEFAULT '0',
  `last_ver` bigint(20) NOT NULL DEFAULT '0',
  `load_time` int(11) NOT NULL DEFAULT '0' COMMENT '记录执行的服务器时间',
  `modify_time` int(11) NOT NULL DEFAULT '0' COMMENT '记录修改的服务器时间',
  `draw_status` tinyint(4) NOT NULL DEFAULT '0',
  `bookmenu_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `make_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `make_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `prodplan_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_wait` tinyint(4) NOT NULL DEFAULT '0',
  `specdetail_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `specdetail_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `makeprice_mode` tinyint(4) NOT NULL DEFAULT '0',
  `original_price` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_buynumber_changed` tinyint(4) NOT NULL DEFAULT '0',
  `ratio_operator_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `child_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `kind_bookmenu_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `specprice_mode` tinyint(4) NOT NULL DEFAULT '0',
  `worker_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_backauth` tinyint(4) NOT NULL DEFAULT '1',
  `service_fee_mode` tinyint(4) NOT NULL DEFAULT '0',
  `service_fee` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `orign_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `addition_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `has_addition` tinyint(4) NOT NULL DEFAULT '0',
  `seat_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  PRIMARY KEY (`instance_id`),
  KEY `idx_load_time` (`load_time`),
  KEY `idx_modify_time` (`modify_time`),
  KEY `idx_oid_eid` (`order_id`,`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='点菜明细表'