FROM --platform=$BUILDPLATFORM golang:1.19.2 as builder
WORKDIR /shifu

ENV GO111MODULE=on
COPY examples/socketDeviceShifu/server/server.go server.go
COPY pkg/logger pkg/logger

# Build the Go app
ARG TARGETOS
ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a \
    -o /output/server server.go

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /output/server server

USER 65532:65532
ENTRYPOINT [ "/server" ]
