#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PROJECT_ROOT=../../../

mvn dependency:build-classpath -f=$PROJECT_ROOT/pom.xml -Dmdep.outputFile=target/sh/cp.txt
CP=`cat $PROJECT_ROOT/target/sh/cp.txt`
CP=./:$CP:$PROJECT_ROOT/target/classes:$PROJECT_ROOT/target/test-classes
java \
-Dlogback.configurationFile=logback.xml \
-XX:MaxDirectMemorySize=8192M \
-XX:+UnlockDiagnosticVMOptions \
-XX:FreqInlineSize=5000 \
-XX:InlineSmallCode=5000 \
-XX:MaxInlineLevel=20 \
-XX:MaxInlineSize=5000 \
-XX:MaxRecursiveInlineLevel=1 \
-cp $CP \
org.apache.drill.exec.RunRootExec $@
