apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetryservice
  namespace: shifu-service
spec:
  selector:
    matchLabels:
      app: telemetryservice
  template:
    metadata:
      labels:
        app: telemetryservice
    spec:
      containers:
      - name: telemetryservice
        image: edgehub/telemetryservice:v0.24.0-rc1
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_LISTEN_PORT
          value: :8080
        - name: EDGEDEVICE_NAMESPACE
          value: "devices"
      serviceAccountName: telemetry-service-sa
---
apiVersion: v1
kind: Service
metadata:
  name: telemetryservice
  namespace: shifu-service
spec:
  selector:
    app: telemetryservice
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
