# Build the manager binary
FROM --platform=$BUILDPLATFORM golang:1.20.2 as builder

WORKDIR /shifu

ENV GO111MODULE=on
ENV GOPRIVATE=github.com/Edgenesis

COPY pkg/deviceshifu/mockdevice deviceshifu/pkg/mockdevice

WORKDIR /shifu/deviceshifu/pkg/mockdevice/mockdevice

COPY go.mod go.mod
COPY go.sum go.sum
COPY pkg/deviceshifu pkg/deviceshifu
COPY pkg/logger pkg/logger
RUN go mod download

# Build the Go app
ARG TARGETOS
ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a \
    -o /output/mockdevice-plate-reader \
    /shifu/deviceshifu/pkg/mockdevice/mockdevice-plate-reader/mockdevice-plate-reader.go

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /output/mockdevice-plate-reader mockdevice-plate-reader

# Command to run the executable
USER 65532:65532
ENTRYPOINT ["/mockdevice-plate-reader"]
