version: '3'
services:
  ranger-build:
    build:
      context: .
      dockerfile: Dockerfile.ranger-build
    image: ranger-build
    container_name: ranger-build
    hostname: ranger-build.example.com
    networks:
      - ranger
    volumes:
      - ~/.m2:/home/ranger/.m2:delegated
      - ./scripts:/home/ranger/scripts
      - ./patches:/home/ranger/patches
      - ./dist:/home/ranger/dist
      - ./../../:/home/ranger/src:delegated
    depends_on:
      - ranger-base
    environment:
      - BRANCH
      - BUILD_HOST_SRC
      - GIT_URL
      - RANGER_VERSION
      - SKIPTESTS

networks:
  ranger:
    name: rangernw
