#!/bin/bash

SERVER_LIST_CONFIG=./rack.properties
function read_config() {
	cat $SERVER_LIST_CONFIG | while read LINE
	do
		ip=${LINE%=*}
		rack=${LINE#*=}
		echo $ip
		echo $rack
		if [ $ip = $1 ]
		then
			echo $rack
			break
		fi
	done
}
read_config