# 日常环境的Dockerfile ： https://lark.alipay.com/aone/docker/rm2g1d
# 用基础镜像地址替换下方镜像地址
FROM reg.docker.alibaba-inc.com/aone-base/tesla-gateway_base:20210413180646

# 健康检查默认3秒钟做一次,默认做100次也就是300秒,这里设置最多等180秒
ENV ali_start_timeout=180

# 设置打开jpda 调试端口。如果需要则打开下面的注释内容
ENV JPDA_ENABLE=1

# 设置spring profile或者自定义的jvm参数。如果需要则打开下面的注释内容
ENV SERVICE_OPTS=-Dspring.profiles.active=test

RUN yum install -b current t-security-xagent -y && sed -i "s/^-application=.*/-application=${APP_NAME}__daily__/g" /home/admin/xagent/conf/xagent.flags

#代表机器组，用于SLS日志收集
ARG identifier_name="daily"
RUN echo ${APP_NAME}_${identifier_name} > /etc/ilogtail/user_defined_id && \
cat /etc/ilogtail/user_defined_id

# 将构建出的主包复制到指定镜像目录中
COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz