# 基础镜像的Dockerfile ： https://lark.alipay.com/aone/docker/rm2g1d
# 基于基础镜像
FROM reg.docker.alibaba-inc.com/aone-base/tesla-nacos_base:20200224162704

# 指定应用名字，配置在$APP_NAME.release文件里
# 从 build.tools.docker.args=--build-arg APP_NAME=${APP_NAME} 传入
ARG APP_NAME
ENV APP_NAME=${APP_NAME}

#拷贝配置文件到conf目录下
COPY conf/testing/cluster.conf /home/admin/${APP_NAME}/conf/


############# test #################
# 健康检查默认3秒钟做一次,默认做100次也就是300秒,这里设置最多等180秒
ENV ali_start_timeout=180

#代表机器组，用于SLS日志收集
ARG identifier_name="daily"
RUN echo ${APP_NAME}_${identifier_name} > /etc/ilogtail/user_defined_id && \
cat /etc/ilogtail/user_defined_id

# 设置打开jpda 调试端口。如果需要则打开下面的注释内容
# ENV JPDA_ENABLE=1

# 设置spring profile或者自定义的jvm参数。如果需要则打开下面的注释内容
# ENV SERVICE_OPTS=-Dspring.profiles.active=testing

# 将构建出的主包复制到指定镜像目录中
COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz