# 基础镜像的Dockerfile ： https://lark.alipay.com/aone/docker/rm2g1d
# 基于基础镜像
FROM reg.docker.alibaba-inc.com/aone-base/tesla-nacos_base:20200224162704


# 指定应用名字，配置在$APP_NAME.release文件里
# 从 build.tools.docker.args=--build-arg APP_NAME=${APP_NAME} 传入
ARG APP_NAME
ENV APP_NAME=${APP_NAME}

#拷贝配置文件到conf目录下
COPY conf/staging/cluster.conf /home/admin/${APP_NAME}/conf/

#代表机器组，用于SLS日志收集
ARG identifier_name="pre"
RUN echo ${APP_NAME}_${identifier_name} > /etc/ilogtail/user_defined_id && \
cat /etc/ilogtail/user_defined_id

############# staging #################
# 设置spring profile或者自定义的jvm参数。如果需要则打开下面的注释内容
# ENV SERVICE_OPTS=-Dspring.profiles.active=staging

# 将构建出的主包复制到指定镜像目录中
COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz