# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM solr:8

USER 0

# Copy Atlas collections config set
RUN  mkdir -p /opt/solr/server/solr/configsets/atlas/conf/lang
COPY ./config/solr/*.*       /opt/solr/server/solr/configsets/atlas/conf/
COPY ./config/solr/lang/*.* /opt/solr/server/solr/configsets/atlas/conf/lang/
RUN chown -R solr:solr /opt/solr/server/solr/configsets/atlas/

# Copy script that creates Atlas collections
COPY ./scripts/atlas-solr-create.sh /docker-entrypoint-initdb.d/

EXPOSE 8983

USER solr
