---
  ## 准备使用npm来打包tis-console-ng包

  - name: Download {{node_assemble_tar}} to {{ tis_release_dir }}
    get_url:
      url: "{{ release_repository }}/{{ item.name }}"
      dest: "{{ tis_release_dir }}/{{ item.name }}"
      force: no
    when: item.when
    with_items:
      - {name: "{{node_assemble_tar}}", when: True}

   #
  - name: mkdir {{nodejs_dir}}
    file:
     path: '{{nodejs_dir}}'
     state: directory

  - name: unpackage nodejs
    unarchive:
     src: "{{ tis_release_dir }}/{{node_assemble_tar}}"
     dest: "{{nodejs_dir}}"
     remote_src: yes


  # set environment variable
  - name: set nodejs and path environment variable
    template:
      src: './template/nodejs.sh'
      dest: "/etc/profile.d/{{ node_name }}.sh"
      mode: '0644'

  # FIXME 目前来看 执行source并没有让上面的任务生效
  - name: source /etc/profile
    shell: source /etc/profile

  - name: git pull {{ng_tis_git_src}}@{{ng_tis_git_branch}} {{ng_tis_src_dir}}
    git:
      repo: '{{ng_tis_git_src}}'
      dest: '{{ng_tis_src_dir}}'
      version: '{{ng_tis_git_branch}}'
      force: yes
      accept_hostkey: yes

  - name: "Download node-modules to {{ ng_tis_src_dir }}/{{ name_ng_tis_node_modules_tar }}"
    get_url:
      url: "{{ release_repository }}/{{ item.name }}"
      dest: "{{ ng_tis_src_dir }}/{{ item.name }}"
      force: no
    when: item.when
    with_items:
      - {name: "{{name_ng_tis_node_modules_tar}}", when: True}

  - name: untar node-modules
    unarchive:
      src: '{{ ng_tis_src_dir }}/{{name_ng_tis_node_modules_tar}}'
      dest: "{{ ng_tis_src_dir }}"
      remote_src: yes

  - name: compile/build ng-tis
    #command: npm run ng:serve-aot
    #shell: npm run ng:serve-aot > exec.log && npm run build:elements >> exec.log
    shell: npm run ng:serve-aot > exec.log
    args:
        chdir: "{{ng_tis_src_dir}}"

#  - name: "copy dist elements from:{{ng_tis_src_dir}}/dist/elements to:{{ng_tis_src_dir}}/dist/{{ng_tis_app_name}}/"
#    synchronize:
#      src: "{{ng_tis_src_dir}}/dist/elements"
#      dest: "{{ng_tis_src_dir}}/dist/{{ng_tis_app_name}}/"
#      recursive: yes
#    delegate_to: "{{ inventory_hostname }}"


  - name: assemble {{ng_tis_app_tar_file_name}} from dir "{{src_root}}/{{ng_tis_app_name}}/dist/" dest {{ tis_release_dir }}/tis
    archive:
      path: "{{ng_tis_src_dir}}/dist/{{ng_tis_app_name}}/*"
      dest: "{{ tis_release_dir }}/tis/{{ng_tis_app_tar_file_name}}"
      remove: yes

  # 需要将完成的包上传到仓库中
