#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

docker build \
	--build-arg BUILD_BASE_IMAGE=maven:3-openjdk-8 \
	--build-arg BASE_IMAGE=openjdk:8 \
	-t apache/drill:$DOCKER_TAG-openjdk-8 \
	-t apache/drill:$DOCKER_TAG \
	.

docker build \
	--build-arg BUILD_BASE_IMAGE=maven:3-openjdk-11 \
	--build-arg BASE_IMAGE=openjdk:11 \
	-t apache/drill:$DOCKER_TAG-openjdk-11 \
	.

docker build \
	--build-arg BUILD_BASE_IMAGE=maven:3-openjdk-17 \
	--build-arg BASE_IMAGE=openjdk:17-slim-bullseye \
	-t apache/drill:$DOCKER_TAG-openjdk-17 \
	.
