on:
  push:
    paths:
      - "native-io/**"
    branches:
      - 'main'
  pull_request:
    paths:
      - "native-io/**"
    branches:
      - 'main'
      - 'release/**'
  workflow_dispatch:

name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-20
          components: clippy
          default: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./native-io -> target"
          key: "ubuntu-latest-clippy"
      - name: Run Clippy
        run: cd native-io && cargo clippy --all-features --package lakesoul-io-c
