{
 "title": "istio service",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(istio_requests_total, destination_service_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(istio_requests_total{destination_service_namespace=\"$namespace\"}, destination_service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "域名服务平均qps请求量(1分钟内)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_service_name,response_code) (irate(istio_requests_total{destination_service_namespace=\"$namespace\",destination_service_name=~\"($service)\"}[1m]))",
     "legendFormat": "{{response_code}} , {{destination_service_name}}"
    }
   ]
  },
  {
   "title": "域名服务吞吐率（1分钟）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_service_name) (irate(istio_request_bytes_sum{destination_service_namespace=\"$namespace\",destination_service_name=~\"($service)\"}[1m]))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "域名服务 平均时延ms(1分钟平均)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (destination_service_name) (rate(istio_request_duration_milliseconds_sum{destination_service_namespace=\"$namespace\",destination_service_name=~\"($service)\"}[1m])/rate(istio_request_duration_milliseconds_count{destination_service_namespace=\"$namespace\",destination_service_name=~\"($service)\"}[1m]))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{job=\"kubelet\", image!=\"\",container_name!=\"POD\",pod=~\".*$service.*\"})",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\",container_name!=\"POD\",pod=~\".*$service.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "pod GPU 显存占用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{exported_pod=~\".*$service.*\"}",
     "legendFormat": "{{exported_pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_pod=~\".*$service.*\"}",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "全部域名服务监控",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_service_name) (istio_requests_total{destination_service_namespace=\"$namespace\"})",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  }
 ]
}