def PROJECT_NAME = (env.JOB_NAME.tokenize('/') as String[])[0]
def BRANCH = env.BRANCH_NAME
def REPO = scm.getUserRemoteConfigs()[0].getUrl()
def TEST_RESULT

pipeline {
    options {
        disableConcurrentBuilds()
    }
    triggers {
        pollSCM('*/2 * * * *')
    }
    parameters {
        string(name: 'ALPINE_X86_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/alibaba_apsara_paas/alpine:v1.0.0', description: '')
        string(name: 'ALPINE_ARM_IMAGE', defaultValue: 'reg.docker.alibaba-inc.com/abm-aone/arm-alpine', description: '')
        string(name: 'X86_IMAGE_PREFIX', defaultValue: 'reg.docker.alibaba-inc.com/abm-aone/openjdk8-jre', description: '')
        string(name: 'ARM_IMAGE_PREFIX', defaultValue: 'reg.docker.alibaba-inc.com/abm-arm64v8/openjdk8-jre', description: '')
    }
    agent any
    stages {
        stage("Clone Repo") {
            steps {
                git credentialsId: "$GIT_CREDENTIAL",
                    url: REPO,
                    branch: BRANCH
            }
        }
        stage('Render & Build & Push Dockerfile') {
            steps {
                sh "bash -c 'ALPINE_IMAGE=${params.ALPINE_X86_IMAGE} envsubst \"\\\$ALPINE_IMAGE\" < Dockerfile.tpl > Dockerfile'"
                script {
                    retry(count: "${env.MAX_RETRY_COUNT}") {
                        applicationImage = docker.build("${params.X86_IMAGE_PREFIX}", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile .")
                        docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) {
                            applicationImage.push()
                        }
                    }
                }

                sh "bash -c 'ALPINE_IMAGE=${params.ALPINE_ARM_IMAGE} envsubst \"\\\$ALPINE_IMAGE\" < Dockerfile.tpl > Dockerfile.arm64v8'"
                script {
                    retry(count: "${env.MAX_RETRY_COUNT}") {
                        applicationImage = docker.build("${params.ARM_IMAGE_PREFIX}", "--pull --no-cache --build-arg TAG=$BRANCH -f ./Dockerfile.arm64v8 .")
                        docker.withRegistry(REGISTRY, REGISTRY_CREDENTIAL) {
                            applicationImage.push()
                        }
                    }
                }
            }
        }
    }
}