{
 "title": "Flink作业监控大盘",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "session_cluster",
    "query": {
     "query": "label_values(flink_jobmanager_numRunningJobs, sessionClusterName)"
    }
   },
   {
    "name": "job_manager",
    "query": {
     "query": "label_values(flink_jobmanager_numRunningJobs, kubernetes_pod_name)"
    }
   },
   {
    "name": "task_manager",
    "query": {
     "query": "label_values(flink_taskmanager_Status_JVM_CPU_Load, kubernetes_pod_name)"
    }
   },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(flink_jobmanager_job_numRestarts, job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "job_manager总数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(flink_jobmanager_numRegisteredTaskManagers{sessionClusterName=\"$session_cluster\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "task_manager总数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(flink_jobmanager_numRegisteredTaskManagers{sessionClusterName=\"$session_cluster\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "运行态作业总数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_jobmanager_numRunningJobs{sessionClusterName=\"$session_cluster\"}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "task_slots总数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(flink_jobmanager_taskSlotsTotal{sessionClusterName=\"$session_cluster\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "基础指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU使用率(job_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(flink_jobmanager_Status_JVM_CPU_Load{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$job_manager\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU使用率(task_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$task_manager\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存使用率(job_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(flink_jobmanager_Status_JVM_Memory_Heap_Used{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$job_manager\"} + flink_jobmanager_Status_JVM_Memory_NonHeap_Used{sessionClusterName=\"$session_cluster\",kubernetes_pod_name=~\"$job_manager\"}) by (kubernetes_pod_name)/ avg(flink_jobmanager_Status_JVM_Memory_Heap_Max{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$job_manager\"} + flink_jobmanager_Status_JVM_Memory_NonHeap_Max{sessionClusterName=\"$session_cluster\",kubernetes_pod_name=~\"$job_manager\"}) by (kubernetes_pod_name)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存使用率(task_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(flink_taskmanager_Status_JVM_Memory_Heap_Used{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$task_manager\"} + flink_taskmanager_Status_JVM_Memory_NonHeap_Used{sessionClusterName=\"$session_cluster\",kubernetes_pod_name=~\"$task_manager\"}) by (kubernetes_pod_name)/ avg(flink_taskmanager_Status_JVM_Memory_Heap_Max{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$task_manager\"} + flink_taskmanager_Status_JVM_Memory_NonHeap_Max{sessionClusterName=\"$session_cluster\",kubernetes_pod_name=~\"$task_manager\"}) by (kubernetes_pod_name)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "JVM指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "活动线程总数(job_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(avg_over_time(flink_jobmanager_Status_JVM_Threads_Count{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$job_manager\"}[1m])) by (kubernetes_pod_name)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "活动线程总数(task_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(avg_over_time(flink_taskmanager_Status_JVM_Threads_Count{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$task_manager\"}[1m])) by (kubernetes_pod_name)",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC次数变化率(job_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "irate(flink_jobmanager_Status_JVM_GarbageCollector_Copy_Count{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$job_manager\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}} ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC次数变化率(task_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "irate(flink_taskmanager_Status_JVM_GarbageCollector_Copy_Count{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$task_manager\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}} ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ClassesLoaded总数(job_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_jobmanager_Status_JVM_ClassLoader_ClassesLoaded{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$job_manager\"}",
     "legendFormat": "{{kubernetes_pod_name}} ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ClassesLoaded总数(task_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_taskmanager_Status_JVM_ClassLoader_ClassesLoaded{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$task_manager\"}",
     "legendFormat": "{{kubernetes_pod_name}} ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heap内存使用量(job_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$job_manager\"}",
     "legendFormat": "{{kubernetes_pod_name}} ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heap内存使用量(task_manager)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{sessionClusterName=\"$session_cluster\", kubernetes_pod_name=~\"$task_manager\"}",
     "legendFormat": "{{kubernetes_pod_name}} ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "作业指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "作业累计重启次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_jobmanager_job_numRestarts{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业累计运行时长",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_jobmanager_job_uptime{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业累计非运行态时长",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_jobmanager_job_downtime{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业CheckPoint失败数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "irate(flink_jobmanager_job_numberOfFailedCheckpoints{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}[5m])",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业CheckPoint延时(延时过高，表示任务存在反压)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_taskmanager_job_task_checkpointStartDelayNanos{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业反压状态(0:未反压 1:存在反压)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_taskmanager_job_task_isBackPressured{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业Bps(Out)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_taskmanager_job_task_numBytesOutPerSecond{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业Bps(In)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_taskmanager_job_task_numBytesInPerSecond{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业记录数(Out)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_taskmanager_job_task_numRecordsOutPerSecond{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "作业记录数(In)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{sessionClusterName=\"$session_cluster\", job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}