{
 "title": "Hoodie_OSS",
 "description": "HUDI Dashboard which has been contributed to the OSS project",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "query": "stats.$dc.gauges.hoodie.*" },
   {
    "name": "Dataset",
    "query": "stats.$dc.gauges.hoodie.$Environment.*"
   },
   {
    "name": "Tablefilter",
    "query": "stats.$dc.gauges.hoodie.$Environment.$Dataset.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataset Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.commit.duration | removeEmpty | sum name | count\n"
      }
     ]
    },
    {
     "title": "Datasets with Metadata Enabled",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieMetadata.basefile.count | removeEmpty | sumSeries name | count\n"
      }
     ]
    },
    {
     "title": "Records Inserted / Day",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.commit.totalInsertRecordsWritten | sum | moving 1d sum\n"
      }
     ]
    },
    {
     "title": "Records Upserted / Day",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.commit.totalUpdateRecordsWritten | sum | moving 1d sum"
      }
     ]
    },
    {
     "title": "Records Written / Day",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.commit.totalRecordsWritten | sum | moving 1d sum"
      }
     ]
    },
    {
     "title": "Active Users",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "countSeries(groupByNode(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.userName.*, -1, 'sum'))"
      }
     ]
    },
    {
     "title": "Versions in Production",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 4, "x": 18, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.version.0.7.0 | sumSeries name | count | alias \"0.7\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.finalize.duration | sumSeries name | count | diff (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.version.0.7.0 | sumSeries name | count)  | alias \"0.5\""
      }
     ]
    },
    {
     "title": "Clean Operations per / Day",
     "type": "stat",
     "description": "Total number of  Clean operations / day ",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.clean.duration | removeEmpty  | isNonNull | sum | moving 1D sum\n"
      }
     ]
    },
    {
     "title": "Commit Operations per / Day",
     "type": "stat",
     "description": "Total number of  Commit operations / day ",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.{commit,deltacommit}.duration | removeEmpty  | isNonNull | sum | moving 1D sum\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Commit Detailed Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commit Duration (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.duration, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "Commit Duration (p95)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nPercentile(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.duration, 95), 5, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Clean Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clean Duration (Top 10)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.clean.duration | sortSeries max desc | head 10\n"
      }
     ]
    },
    {
     "title": "Clean File Deleted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.clean.numFilesDeleted | sortSeries max desc | head 10\n"
      }
     ]
    },
    {
     "title": "Clean Duration (Max, P95, P99)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.clean.duration | max | alias \"Maximum\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.clean.duration | sum | nPercentile 95 | alias \"P95\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.clean.duration | sum | nPercentile 99 | alias \"P99\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.clean.duration | sum | moving 1D avg | alias \"AVG\"\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataset Detailed Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of NEW Files Generated (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.totalFilesInsert.count, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "Number of EXISTING files versioned (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.totalFilesUpdate.count, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "Number of OLD files deleted (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.clean.numFilesDeleted.count, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "Number of NEW records Added (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.totalInsertRecordsWritten.count, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "Number of OLD records updated (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.totalUpdateRecordsWritten.count, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "How many records (INSERT/UPDATE/COPY) written? (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.totalRecordsWritten.count, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "How many partitions updated? (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.totalPartitionsWritten.count, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "How many bytes written? (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.commit.totalBytesWritten.count, 10), 1, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Hadoop & RPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "HDFS RPC Calls (outside .hoodie folder)",
     "type": "graph",
     "description": "Count of various types of HDFS RPC calls for files outside the .hoodie folder",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.create | removeEmpty | sumSeries  | alias \"create\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.rename | removeEmpty | sumSeries  | alias \"rename\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.delete | removeEmpty | sumSeries  | alias \"delete\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.listStatus | removeEmpty | sumSeries  | alias \"listStatus\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.mkdirs | removeEmpty | sumSeries  | alias \"mkdirs\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.getFileStatus | removeEmpty | sumSeries  | alias \"getFileStatus\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.globStatus | removeEmpty | sumSeries  | alias \"globStatus\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.listFiles | removeEmpty | sumSeries  | alias \"listFiles\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.open | removeEmpty | sumSeries  | alias \"open\"\n"
      }
     ]
    },
    {
     "title": "HDFS RPC Calls (outside .hoodie folder) - read / write",
     "type": "graph",
     "description": "Count of various types of HDFS RPC calls for files outside the .hoodie folder",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.read | removeEmpty | sumSeries  | alias \"read\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.write | removeEmpty | sumSeries  | alias \"write\"\n"
      }
     ]
    },
    {
     "title": "HDFS Read / Write Bytes (outside .hoodie folder)",
     "type": "graph",
     "description": "Total bytes for read/writeHDFS RPC calls",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.read.totalBytes | removeEmpty | sumSeries  | alias \"read\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem.write.totalBytes | removeEmpty | sumSeries  | alias \"write\"\n"
      }
     ]
    },
    {
     "title": "HDFS RPC Calls (.hoodie folder)",
     "type": "graph",
     "description": "Count of various types of HDFS RPC calls for files inside the .hoodie folder",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.create | removeEmpty | sumSeries  | alias \"create\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.rename | removeEmpty | sumSeries  | alias \"rename\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.delete | removeEmpty | sumSeries  | alias \"delete\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.listStatus | removeEmpty | sumSeries  | alias \"listStatus\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.mkdirs | removeEmpty | sumSeries  | alias \"mkdirs\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.getFileStatus | removeEmpty | sumSeries  | alias \"getFileStatus\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.globStatus | removeEmpty | sumSeries  | alias \"globStatus\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.listFiles | removeEmpty | sumSeries  | alias \"listFiles\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.open | removeEmpty | sumSeries  | alias \"open\"\n"
      }
     ]
    },
    {
     "title": "HDFS RPC Calls (.hoodie folder) - read / write",
     "type": "graph",
     "description": "Count of various types of HDFS RPC calls for files inside the .hoodie folder",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.read | removeEmpty | sumSeries  | alias \"read\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.write | removeEmpty | sumSeries  | alias \"write\"\n"
      }
     ]
    },
    {
     "title": "HDFS Read / Write Bytes (.hoodie folder)",
     "type": "graph",
     "description": "Total bytes for read/writeHDFS RPC calls within .hoodie folder",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.read.totalBytes | removeEmpty | sumSeries  | alias \"read\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.write.totalBytes | removeEmpty | sumSeries  | alias \"write\"\n"
      }
     ]
    },
    {
     "title": "HDFS RPC Calls Timings",
     "type": "graph",
     "description": "Average timings of various types of HDFS RPC calls",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.delete.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.delete | removeEmpty | sumSeries) | alias \"delete\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.create.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.create | removeEmpty | sumSeries) | alias \"create\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.rename.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.rename | removeEmpty | sumSeries) | alias \"rename\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.listStatus.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.listStatus | removeEmpty | sumSeries) | alias \"listStatus\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.mkdirs.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.mkdirs | removeEmpty | sumSeries) | alias \"mkdirs\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.getFileStatus.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.getFileStatus | removeEmpty | sumSeries) | alias \"getFileStatus\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.globStatus.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.globStatus | removeEmpty | sumSeries) | alias \"globStatus\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.listFiles.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.listFiles | removeEmpty | sumSeries) | alias \"listFiles\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.read.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.read | removeEmpty | sumSeries) | alias \"read\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.write.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.write | removeEmpty | sumSeries) | alias \"write\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.open.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.open | removeEmpty | sumSeries) | alias \"open\""
      }
     ]
    }
   ]
  },
  {
   "title": "Timelines Metrics 0.7v",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total API Calls",
     "type": "graph",
     "description": "Counts of of various types of TimelineService API calls",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.ALL_FILEGROUPS_FOR_PARTITION | removeEmpty | sum | alias \"ALL_FILEGROUPS_FOR_PARTITION\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.ALL_REPLACED_FILEGROUPS_PARTITION | removeEmpty | sum | alias \"ALL_REPLACED_FILEGROUPS_PARTITION\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.LATEST_DATA_FILES_BEFORE_ON_INSTANT | removeEmpty | sum | alias \"LATEST_DATA_FILES_BEFORE_ON_INSTANT\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.LATEST_PARTITION_DATA_FILE | removeEmpty | sum | alias \"LATEST_PARTITION_DATA_FILE\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.PEDING_COMPACTION_OPS | removeEmpty | sum | alias \"PEDING_COMPACTION_OPS\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.LATEST_ALL_DATA_FILES | removeEmpty | sum | alias \"LATEST_ALL_DATA_FILES\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.LATEST_DATA_FILE_ON_INSTANT | removeEmpty | sum | alias \"LATEST_DATA_FILE_ON_INSTANT\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.ALL_DATA_FILES | removeEmpty | sum | alias \"ALL_DATA_FILES\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.LATEST_DATA_FILES_RANGE_INSTANT | removeEmpty | sum | alias \"LATEST_DATA_FILES_RANGE_INSTANT\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.ALL_REPLACED_FILEGROUPS_BEFORE | removeEmpty | sum | alias \"ALL_REPLACED_FILEGROUPS_BEFORE\"\n"
      }
     ]
    },
    {
     "title": "Timing for operations (Avg)",
     "type": "graph",
     "description": "Timings of various types of TimelineService API calls",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_TIME | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_CALLS | removeEmpty | sumSeries) | alias \"API Time\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_CHECK_TIME | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_CALLS | removeEmpty | sumSeries) | alias \"Check Time\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_REFRESH_TIME | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_CALLS | removeEmpty | sumSeries) | alias \"Refresh Time\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_HANDLE_TIME | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_CALLS | removeEmpty | sumSeries) | alias \"Handle Time\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.WRITE_VALUE_TIME | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.WRITE_VALUE_CNT | removeEmpty | sumSeries) | alias \"Json Encoding Time\""
      }
     ]
    },
    {
     "title": "TimelineService API vs HDFS RPC Time",
     "type": "graph",
     "description": "Timings of various types of TimelineService API calls",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_TIME | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_CALLS | removeEmpty | sumSeries) | nPercentile 95 | alias \"TimeLine Service P95\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.listStatus.totalDuration | removeEmpty | sumSeries | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystem*.listStatus | removeEmpty | sumSeries) | nPercentile 95 | alias \"HDFS\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_TIME | removeEmpty | sumSeries | moving 1D sum | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.TimelineService.TOTAL_API_CALLS | removeEmpty | sumSeries | moving 1D sum) | alias \"TimeLine Service AVG\""
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata Metrics (RFC-15)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "ListStatus Calls Required / Day (.hoodie folder)",
     "type": "stat",
     "description": "Total number of RPC calls saved / day due to the use of Metadata Table",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieWrapperFileSystemMetaFolder.listStatus | sum | moving 1D sum\n"
      }
     ]
    },
    {
     "title": "ListStatus Calls Required / Day (outside .hoodie folder)",
     "type": "stat",
     "description": "Total number of RPC calls saved / day due to the use of Metadata Table",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.{HoodieMetadata,HoodieWrapperFileSystem}.{lookup_files.count,lookup_partitions.count,listStatus} | removeEmpty |  sum | moving 1D sum\n"
      }
     ]
    },
    {
     "title": "Total HUDI listStatus Calls / Day",
     "type": "stat",
     "description": "Total number of RPC calls saved / day due to the use of Metadata Table",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.{HoodieWrapperFileSystemMetaFolder,HoodieWrapperFileSystem,HoodieMetadata}.{lookup_files.count,lookup_partitions.count,listStatus} | sum | moving 1D sum\n"
      }
     ]
    },
    {
     "title": "Total listStatus Calls  Removed / Day",
     "type": "stat",
     "description": "Total number of RPC calls saved / day due to the use of Metadata Table",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieMetadata.{lookup_files,lookup_partitions}.count | sum | moving 1D sum\n"
      }
     ]
    },
    {
     "title": "% of listStatus Calls  Removed / Day (of Total)",
     "type": "gauge",
     "description": "Percent of listStatus Calls  Removed / Day due to the use of Metadata Table",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieMetadata.{lookup_files.count,lookup_partitions.count} | sum | moving 1D sum | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.{HoodieWrapperFileSystemMetaFolder,HoodieWrapperFileSystem,HoodieMetadata}.{lookup_files.count,lookup_partitions.count,listStatus} | removeEmpty | sum | moving 1D sum ) | scale 100\n"
      }
     ]
    },
    {
     "title": "% of listStatus Calls  Removed / Day (As Implemented)",
     "type": "gauge",
     "description": "Percent of listStatus Calls Removed / Day due to the use of Metadata Table as implemented in current production release of HUDI.",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.HoodieMetadata.{lookup_files.count,lookup_partitions.count} | sum | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.$Tablefilter.{HoodieWrapperFileSystem,HoodieMetadata}.{lookup_files.count,lookup_partitions.count,listStatus} | sum) | scale 100\n"
      }
     ]
    },
    {
     "title": "DeltaCommit - Max Partitions Written",
     "type": "stat",
     "description": "Maximum Partitions written in each DeltaCommit (should be 1)",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.deltacommit.totalPartitionsWritten | max\n"
      }
     ]
    },
    {
     "title": "DeltaCommit - Max Files Updated",
     "type": "stat",
     "description": "Maximum files updated in each DeltaCommit (should be 1)",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.deltacommit.totalFilesUpdate | max\n"
      }
     ]
    },
    {
     "title": "DeltaCommit - Max records written",
     "type": "stat",
     "description": "Maximum records written in a Deltacommit",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.deltacommit.totalRecordsWritten | max\n"
      }
     ]
    },
    {
     "title": "Compaction - Max Partitions Written",
     "type": "stat",
     "description": "Maximum Partitions written in each Compaction (should be 1)",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.compaction.totalPartitionsWritten | max\n"
      }
     ]
    },
    {
     "title": "Compaction - Max LogFiles Compacted",
     "type": "stat",
     "description": "Maximum log files compacted in each Compaction (should be 1)",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.compaction.totalLogFilesCompacted | max\n"
      }
     ]
    },
    {
     "title": "Compaction - Max Records Written",
     "type": "stat",
     "description": "Maximum records and partitions written in a Compaction",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.compaction.totalRecordsWritten | max\n"
      }
     ]
    },
    {
     "title": "Timings for various operations",
     "type": "graph",
     "description": "Total time taken for various operations on the metadata table",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.sync.totalDuration | removeEmpty | sum  | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.sync.count | removeEmpty | sum ) | alias \"sync\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.scan.totalDuration | removeEmpty | sum  | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.scan.count | removeEmpty | sum ) | alias \"scan\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.initialize.totalDuration | removeEmpty | sum  | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.initialize.count | removeEmpty | sum ) | alias \"initialize\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.lookup_partitions.totalDuration | removeEmpty | sum  | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.lookup_partitions.count | removeEmpty | sum ) | alias \"lookup_partitions\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.lookup_files.totalDuration | removeEmpty | sum  | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.lookup_files.count | removeEmpty | sum ) | alias \"lookup_files\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.basefile_read.totalDuration | removeEmpty | sum  | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.basefile_read.count | removeEmpty | sum ) | alias \"basefile_read\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.validate_partitions.totalDuration | removeEmpty | sum  | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.validate_partitions.count | removeEmpty | sum ) | alias \"validate_partitions\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.validate_files.totalDuration | removeEmpty | sum  | divideSeries (fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.validate_files.count | removeEmpty | sum ) | alias \"validate_files\"\n"
      }
     ]
    },
    {
     "title": "Counts of various operations ",
     "type": "graph",
     "description": "Number of lookups for list of partitions or files within a partition from the metadata table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.lookup_partitions.count | removeEmpty | sum  | alias \"lookup_partitions\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.lookup_files.count | removeEmpty | sum  | alias \"lookup_files\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.sync.count | removeEmpty | sum  | alias \"sync\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.scan.count | removeEmpty | sum  | alias \"scan\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.initialize.count | removeEmpty | sum  | alias \"initialize\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.basefile_read.count | removeEmpty | sum  | alias \"basefile_read\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.validate_partitions.count | removeEmpty | sum  | alias \"validate_partitions\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.validate_files.count | removeEmpty | sum  | alias \"validate_files\""
      }
     ]
    },
    {
     "title": "Metadata Basefile Size",
     "type": "graph",
     "description": "Total size of all metadata base files (HFIle) created",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.basefile.size | removeEmpty | sum name | aliasByTags name\n"
      }
     ]
    },
    {
     "title": "Metadata Basefile Count",
     "type": "graph",
     "description": "Number of metadata base files (HFIle) created",
     "gridPos": { "h": 7, "w": 7, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.basefile.count | removeEmpty | sum name | aliasByTags name\n"
      }
     ]
    },
    {
     "title": "Metadata Logfile Size",
     "type": "graph",
     "description": "Total size of all metadata log files created",
     "gridPos": { "h": 7, "w": 6, "x": 13, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.logfile.size | removeEmpty | sum name | aliasByTags name\n"
      }
     ]
    },
    {
     "title": "Metadata Logfile Count",
     "type": "graph",
     "description": "Number of metadata log files created",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.logfile.count | removeEmpty | sum name | aliasByTags name\n"
      }
     ]
    },
    {
     "title": "Metadata Table Actions Duration (Average)",
     "type": "graph",
     "description": "Maximum Time taken for various actions on the Metadata Table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.deltacommit.duration | removeEmpty | avg | alias \"deltacommit\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.compaction.duration | removeEmpty | avg | alias \"compaction\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.finalize.duration | removeEmpty | avg | alias \"finalize\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.clean.duration | removeEmpty | avg | alias \"clean\"\n"
      }
     ]
    },
    {
     "title": "Metadata Table Actions Duration (Max)",
     "type": "graph",
     "description": "Maximum Time taken for various actions on the Metadata Table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.deltacommit.duration | removeEmpty | max | alias \"deltacommit\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.compaction.duration | removeEmpty | max | alias \"compaction\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.finalize.duration | removeEmpty | max | alias \"finalize\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.clean.duration | removeEmpty | max | alias \"clean\"\n"
      }
     ]
    },
    {
     "title": "Metadata Table Errors",
     "type": "graph",
     "description": "Number of error within the metadata table. ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.validate_errors.count | removeEmpty | sum name | alias \"validate_errors\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.bootstrap_error.count | removeEmpty | sum name | alias \"bootstrap_errors\""
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}.HoodieMetadata.rebootstrap.count | removeEmpty | sum name | alias \"rebootstrap\""
      }
     ]
    },
    {
     "title": "Metadata Table Record Writes",
     "type": "graph",
     "description": "Records written to Metadata Table in each operation",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.deltacommit.totalInsertRecordsWritten | removeEmpty | sum | alias \"deltacommit.inserts\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.deltacommit.totalUpdateRecordsWritten | removeEmpty | sum | alias \"deltacommit.updates\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.deltacommit.totalRecordsWritten | removeEmpty | sum | alias \"deltacommit.total_records\"\n"
      },
      {
       "target": "fetch service:hoodie type:gauges dc:$dc name:$Environment.$Dataset.${Tablefilter}_metadata.compaction.totalRecordsWritten | removeEmpty | sum | alias \"compaction.total_records\"\n"
      }
     ]
    }
   ]
  },
  {
   "title": "HBase Index Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of HBase Inserts",
     "type": "graph",
     "description": "Number of HBase Inserts",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "    fetch service:hoodie datafeed:* name:hbase_num_puts env:production dc:dca* owner:* frequency:* source:* | sumSeries datafeed | sortSeries current desc | aliasByTags datafeed dc | removeEmpty | averageSeries | alias \"Average\""
      },
      {
       "target": "    fetch service:hoodie datafeed:* name:hbase_num_puts env:production dc:dca* owner:* frequency:* source:* | sumSeries datafeed | sortSeries current desc | aliasByTags datafeed dc | removeEmpty | minSeries | alias \"Min\""
      },
      {
       "target": "    fetch service:hoodie datafeed:* name:hbase_num_puts env:production dc:dca* owner:* frequency:* source:* | sumSeries datafeed | sortSeries current desc | aliasByTags datafeed dc | removeEmpty | maxSeries | alias \"Max\""
      }
     ]
    },
    {
     "title": "Total HBase Inserts (Summed 15m interval)",
     "type": "graph",
     "description": "Total number of HBase Inserts",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "    fetch service:hoodie datafeed:* name:hbase_num_puts env:production dc:dca* owner:* frequency:* source:* | sumSeries | summarize 15m | alias \"Total\" | removeEmpty"
      }
     ]
    },
    {
     "title": "HBase puts time taken",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie datafeed:* name:hbase_qps_resources_actual_puts_time_secs env:production dc:* owner:* frequency:* source:* | sumSeries datafeed | sortSeries current desc | aliasByTags datafeed dc | removeEmpty | averageSeries | alias \"Average\""
      },
      {
       "target": "fetch service:hoodie datafeed:* name:hbase_qps_resources_actual_puts_time_secs env:production dc:* owner:* frequency:* source:* | sumSeries datafeed | sortSeries current desc | aliasByTags datafeed dc | removeEmpty | minSeries | alias \"Min\""
      },
      {
       "target": "fetch service:hoodie datafeed:* name:hbase_qps_resources_actual_puts_time_secs env:production dc:* owner:* frequency:* source:* | sumSeries datafeed | sortSeries current desc | aliasByTags datafeed dc | removeEmpty | maxSeries | alias \"Max\""
      }
     ]
    },
    {
     "title": "Total HBase puts time taken (Summed 15m interval)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie datafeed:* name:hbase_qps_resources_actual_puts_time_secs env:production dc:* owner:* frequency:* source:* | sumSeries | summarize 15m   | alias \"Total\" | removeEmpty"
      }
     ]
    },
    {
     "title": "Total HBase Clients (Summed 15m interval)",
     "type": "graph",
     "description": "Total number of HBase Clients (Datasets)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "    fetch service:hoodie datafeed:* name:hbase_num_puts env:production dc:dca* owner:* frequency:* source:* | sumSeries datafeed | count  | summarize 15m | removeEmpty"
      }
     ]
    },
    {
     "title": "Average HBase Put Time / Key (Summed 15m interval)",
     "type": "graph",
     "description": "Total number of HBase Inserts",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "fetch service:hoodie datafeed:* name:hbase_qps_resources_actual_puts_time_secs env:production dc:* owner:* frequency:* source:* | sumSeries | summarize 15m   | alias \"Total\" | removeEmpty | divideSeries (    fetch service:hoodie datafeed:* name:hbase_num_puts env:production dc:dca* owner:* frequency:* source:* | sumSeries | summarize 15m | alias \"Total\" | removeEmpty) | alias \"Average\""
      }
     ]
    },
    {
     "title": "Cluster HDFS Storage Usage (Carbon + Magnesium)",
     "type": "graph",
     "description": "HDFS Storage used by the cluster",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "alias(maxSeries(servers.*.hadoop.{dca1-carbon-prod,magnesium}.hdfs.namenode.CapacityTotalGB), \"Total Capacity\")"
      },
      {
       "refCount": 1,
       "target": "alias(maxSeries(servers.*.hadoop.{dca1-carbon-prod,magnesium}.hdfs.namenode.CapacityUsedGB), \"Capacity Used\")"
      },
      {
       "target": "alias(asPercent(#B, #A), 'HDFS usage')",
       "targetFull": "alias(asPercent(alias(maxSeries(servers.*.hadoop.{dca1-carbon-prod,magnesium}.hdfs.namenode.CapacityUsedGB), \"Capacity Used\"), alias(maxSeries(servers.*.hadoop.{dca1-carbon-prod,magnesium}.hdfs.namenode.CapacityTotalGB), \"Total Capacity\")), 'HDFS usage')"
      }
     ]
    },
    {
     "title": "HBase Usage (Top 25 tables)",
     "type": "graph",
     "description": "Size of HBase table for the top 25 tables",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "highestMax(groupByNode(servers.hadoop*.hbase.$HbaseClusters.regionserver.tables.*.*.MaxStoreFileSize, 7, 'maxSeries'), 25)"
      }
     ]
    },
    {
     "title": "Write Requests per min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(percentileOfSeries(removeAboveValue(nonNegativeDerivative(servers.hadoop*.hbase.$HbaseClusters.regionserver.writeRequestCount), 500000), 95, 'false'), '95 percentile')"
      },
      {
       "target": "alias(percentileOfSeries(removeAboveValue(nonNegativeDerivative(servers.hadoop*.hbase.$HbaseClusters.regionserver.writeRequestCount), 500000), 50, 'false'), 'median')"
      }
     ]
    },
    {
     "title": "Total Region Servers",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 45 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "countSeries(averageAbove(servers.hadoop*.hbase.$HbaseClusters.regionserver.MemHeapUsedM, 1))"
      }
     ]
    }
   ]
  },
  {
   "title": "Deltastreamer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deltastreamer Hive Sync Duration (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.deltastreamer.hiveSyncDuration, 10), 1, 6)"
      }
     ]
    },
    {
     "title": "Transformation + Commit Duration (Top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.deltastreamer.duration, 10), 1, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Clustering",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clustering duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.$dc.gauges.hoodie.$Environment.$Tablefilter.replacecommit.duration, 1, 5)"
      }
     ]
    },
    {
     "title": "Total Partitions Written",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.$dc.gauges.hoodie.$Environment.$Tablefilter.replacecommit.totalPartitionsWritten, 1, 5)"
      }
     ]
    },
    {
     "title": "File Creation time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.$dc.gauges.hoodie.$Environment.$Tablefilter.replacecommit.fileCreationTime, 1, 5)"
      }
     ]
    },
    {
     "title": "Total Files Inserted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.$dc.gauges.hoodie.$Environment.$Tablefilter.replacecommit.totalFilesInsert, 1, 5)"
      }
     ]
    },
    {
     "title": "Total Inserted records written",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.$dc.gauges.hoodie.$Environment.$Tablefilter.replacecommit.totalInsertRecordsWritten, 1, 5)"
      }
     ]
    },
    {
     "title": "Cluster job failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "stats.$dc.gauges.hoodie.$Environment.$Tablefilter.replacecommit.job.failure"
      }
     ]
    },
    {
     "title": "Encryption time taken 95th percentile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "scale(nPercentile(stats.$dc.gauges.hoodie.$Environment.$Tablefilter.replacecommit.encryptRecord, 95), 0.000001)"
      }
     ]
    },
    {
     "title": "Total time taken to transform record 95th percentile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "scale(nPercentile(stats.$dc.gauges.hoodie.$Environment.$Tablefilter.replacecommit.totalTransformRecord, 95), 0.000001)"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Time Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per record write time (INSERTS)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "divideSeries(sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.cumulativeParquetWriteTimeInUSec.CREATE), #A)",
       "targetFull": "divideSeries(sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.cumulativeParquetWriteTimeInUSec.CREATE), sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.totalRecordsWritten.CREATE))"
      }
     ]
    },
    {
     "title": "Per record write time (UPDATES)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "divideSeries(sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.cumulativeParquetWriteTimeInUSec.MERGE), #A)",
       "targetFull": "divideSeries(sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.cumulativeParquetWriteTimeInUSec.MERGE), sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.totalRecordsWritten.MERGE))"
      }
     ]
    },
    {
     "title": "Cumulative Write times (INSERTS)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.cumulativeParquetWriteTimeInUSec.CREATE)"
      }
     ]
    },
    {
     "title": "Cumulative Write times (UPDATES)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.cumulativeParquetWriteTimeInUSec.MERGE)"
      }
     ]
    },
    {
     "title": "Total Records Written (INSERTS)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.totalRecordsWritten.CREATE)"
      }
     ]
    },
    {
     "title": "Total Records Written (UPDATES)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sumSeries(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.totalRecordsWritten.MERGE)"
      }
     ]
    },
    {
     "title": "Per Record Write Times (INSERT - 200 slowest)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "highestMax(stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.writeTimePerRecordInUSec.CREATE.*.*.*.*, 200)"
      }
     ]
    },
    {
     "title": "Per Record Write Timer (UPDATES - 200 slowest)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "µs" }
     ]
    }
   ]
  },
  {
   "title": "Bloom  Index metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bloom Index search time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.bloomIndexSearchTime"
      }
     ]
    },
    {
     "title": "Bloom Index File Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "stats.$dc.gauges.hoodie.$Environment.$Dataset.$Tablefilter.DistributedMetrics.*.consolidated.bloomIndexFileRecords"
      }
     ]
    }
   ]
  }
 ]
}