site_name: Arctic
site_description: Arctic is a pluggable streaming lakehouse service layer on top of hive and iceberg

docs_dir: '../../docs/en'
site_dir: '../../generated/en'
remote_name: arctic-site
use_directory_urls: true
repo_url: https://github.com/NetEase/arctic
repo_name: NetEase/arctic
edit_uri: ""

# pip install mkdocs-material
theme:
  font:
    text: sans-serif
  name: material
  language: en
  favicon: images/favicon.ico
  logo: images/arctic_banner.png
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github

extra:
  search:
    language: 'en'
  alternate:
    - name: 中文
      link: /ch/
      lang: zh-Hant
    - name: English
      link: /en/
      lang: en

copyright: "Copyright 2018-2021"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Overview: index.md


plugins:
  - search

extra_css:
  - stylesheets/extra.css