version: "1.1"

on:
  push:
    branches:
      - release/*
    tags:
      - v*

envs:
  FOR_COMMUNITY: "true"

stages:
  - stage:
      - git-checkout:
          alias: erda-ui
          params:
            depth: 1
  - stage:
      - extract-repo-version:
          alias: ui-version
          params:
            git_dir: ${{ dirs.erda-ui }}
  - stage:
      - js-build:
          alias: build-erda-ui
          params:
            build_cmd:
              - npm i -g @erda-ui/cli@1.0.23
              - npm i -g pnpm
              - erda-ui init -s --online
              - erda-ui build -s -o
            node_version: 12
            workdir: ${{ dirs.erda-ui }}
          caches:
            - path: ${{ dirs.erda-ui }}/node_modules
            - path: ${{ dirs.erda-ui }}/core/node_modules
            - path: ${{ dirs.erda-ui }}/shell/node_modules
            - path: ${{ dirs.erda-ui }}/scheduler/node_modules
            - path: ${{ dirs.erda-ui }}/modules/uc/node_modules
            - path: ${{ dirs.erda-ui }}/modules/market/node_modules
          resources:
            cpu: 2
            mem: 6144
  - stage:
      - dockerfile:
          alias: build-erda-ui-image
          version: "1.0"
          params:
            workdir: ${{ dirs.build-erda-ui }}
            path: Dockerfile
            image:
              name: ui-ce
              tag: ${{ outputs.ui-version.image_tag }}
            registry:
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
              password: ${{ configs.docker_registry_password }}
          resources:
            cpu: 2
            mem: 6144
  - stage:
      - release:
          alias: release-ui-community
          params:
            tag_version: ${{ outputs.ui-version.version }}
            dice_yml: ${erda-ui}/erda.yml
            image:
              ui: ${{ outputs.build-erda-ui-image.image }}
